Josh-XT/AGiXT

- frontend/src/AgentControls.js
- frontend/src/AgentList.js
- package-lock.json
Fixed the request spam and made the UI just a tiny bit nicer.
> Do you really hate front end?

- app.py
- babyagi.py
- frontend/src/AgentControls.js
- frontend/src/AgentList.js
- package-lock.json
- static/swagger.json
> Updated front end and API.

- Dockerfile-backend
Adding dependencies to Dockerfile-backend
- git
- libgomp1
> Adding dependencies to Dockerfile-backend

- AgentLLM.py
- Config.py
- Dockerfile-backend
- app.py
- prompts/Create New Command.txt
- prompts/Execution.txt
- prompts/Instruction.txt
- prompts/Prioritize.txt
- prompts/Task Creation.txt
Making tasks save their outputs to files so that they're not lost after the task is complete.
> Add Custom Prompt Endpoints, Update Tasks to save outputs to files.

- AgentLLM.py
- model-prompts/bard/priority.txt
- model-prompts/bing/priority.txt
- model-prompts/chatgpt/priority.txt
- model-prompts/default/priority.txt
- model-prompts/gpt-3.5-turbo/priority.txt
- model-prompts/gpt-4/priority.txt
- model-prompts/vicuna/priority.txt
- prompts/Prioritize.txt
- requirements-mac.txt
- requirements.txt
- testtask.py
Fixed a bunch of stuff with the task objective agent.  Seems to work!
Also improved context by using spacy instead of assuming words are tokens since that was causing a lot of stuff to be shoved into context unnecessarily.
> Stable Back End for v1.0.8

- commands/work_with_ai.py
Commands to enable your agent to ask another agent that you've configured a question, or to instruct it to complete a task.
> "Work with AI" Commands

- commands/work_with_ai.py
- docker-compose.yml
Potential Bug fixes for #94, #79, #82
- Updated docker-compose to be built rather than pulling from GitHub
- Added check to see if agent.name is empty before trying to use it.
> Potential Bug fixes for #94, #79, #82

- app.py
- docker-compose-mac.yml
- docker-compose.yml
- docs/README.md
- frontend/components/agent/AgentAdmin.js
- frontend/components/agent/AgentChat.js
- frontend/components/agent/AgentCommand.js
- frontend/components/agent/AgentCommandList.js
- frontend/components/agent/AgentControl.js
- frontend/components/agent/AgentInstruct.js
- frontend/components/agent/AgentObjective.js
- frontend/components/content/DoubleSidedMenu.js
- frontend/pages/agent/[agent].js
- frontend/pages/agent/index.js
- frontend/pages/chain/[chain].js
- frontend/pages/chain/index.js
- frontend/pages/new/agent.js
- frontend/pages/new/chain.js
- frontend/pages/new/prompt.js
- frontend/pages/prompt/[prompt].js
- frontend/pages/prompt/index.js
- frontend/pages/provider/[provider].js
- frontend/pages/provider/index.js
- notebook.ipynb
- notebooks/bard.ipynb
- notebooks/chatgpt.ipynb
- notebooks/llamacpp.ipynb
- notebooks/oobabooga.ipynb
- notebooks/openai.ipynb
- provider/oobabooga.py
Update port to 7437 from 5000 for #93, #79, and #61
> Update port to 7437 from 5000 for #93, #79, and #61

- notebooks/oobabooga.ipynb
- provider/oobabooga.py
This should fix the oobabooga functionality by using the new api.
Also updated the notebook example.
> fix oobabooga api access

- Commands.py
After these fixes, I am finally able to execute commands on gpt-3.5-turbo.
This should close #105
> Fix the remaining issues in the command execution pipeline

- provider/huggingchat.py
> Huggingchat

- Commands.py
- Config.py
Fixing organization in commands init so that agent_name is defined before used.
> Bugfixes 2

- docs/README.md
- change status button to alpha
> - Readme: change status button to alpha

- provider/huggingchat.py
Fix for #158, removed unnecessary failure message on success.
> Fix for #158

- docker-compose-mac.yml
- docker-compose.yml
Potential fix for #143 and #79
> Update compose files

- API-Tests.ipynb
- provider/huggingchat.py
Fix and test huggingchat for #169
> Fix and test huggingchat #169 

- provider/huggingchat.py
> Switching huggingchat from stream true to false

- provider/huggingchat.py
Add more error handling for huggingchat
> Add more error handling for huggingchat

- frontend/components/systems/agent/tabs/AgentConfigure.js
- frontend/pages/_app.js
- frontend/pages/provider/[provider].js
- frontend/pages/provider/index.js
Potential fix for ECONNREFUSED error
This adds the missing paths in the URLs, avoiding redirects to localhost:80 for invalid links.
Allows the frontend to communicate with the backend in cases where the link was previously invalid
Potentially fixes #182 , #184 , #188 , #189
Only tested it on my system; after the changes, the agents page loads sometimes but no longer gives the error. Requesting testing by other users.
> add missing path to urls

- frontend/pages/_app.js
This most certainly doesn't make sense because I doubt the frontend has access to process.env (I think this issue was introduced with mindless search & replace), but at least it gets rid of the errors which break the frontend
quick hotfix
frontend is borked
yes
> hotfix _app.js

- frontend/components/systems/agent/tabs/AgentConfigure.js
Fixed provider settings drop down
> Fixed provider settings drop down

- frontend/components/systems/agent/tabs/AgentChat.js
> Fix chat #183

- Config/Agent.py
Agent config was appending instead of over writing, fixed this.
> Fix agent config save #199

- Config/Agent.py
- app.py
Fix agent config and command toggles
> Fix agent config and command toggles

- model-prompts/vicuna/execute.txt
- model-prompts/vicuna/instruct.txt
- model-prompts/vicuna/priority.txt
- model-prompts/vicuna/task.txt
Vicuna 1.0 prompts engineered by Electrofried
> Vicuna 1.0 prompts engineered by Electrofried

- AgentLLM.py
Instruct prompt was referencing the wrong variable.
> Fix instruct

- frontend/components/systems/agent/tabs/AgentChat.js
- frontend/components/systems/agent/tabs/AgentInstruct.js
Replace handleSendInstruction with the correct function
Allows the user to send messages/instructions to the agent on enter key press.
Fixes #215
Tested locally.
> replace invalid send function refs

- provider/huggingchat.py
Waiting for 3 seconds seems to be enough. Could be lower, actually
yes, it works
> fix - gracefully handle 'model is overloaded' message from huggingchat

- frontend/components/systems/agent/tabs/AgentInstruct.js
it was just confusing when I accidentally hit 'instruct' and weird things started happening
> fix - don't instruct empty messages

- provider/bard.py
Bard provider needed rework to continue conversation after a certain point.
> Rework bard provider

- AgentLLM.py
- Commands.py
Solves the issue of commands failing to execute due to lack of arguments.
Improves List creation by agents.
Commands were failing due to lack of arguments being detected with local LLM's, this should resolve the issue by instead returning the error.
Also changed list creation to first check for a number in the first 10 characters after splitting lines and strip anything before, then order the lists and filter out blank or malformed lines.
Lists generated by local providers often contained explanations, or content unrelated to the task. This should help resolve that while improving the general list creation without damaging the ability of more complex providers like openAI to also perform the tasks/
I ran the generation for a few hours using different prompts/agents and the task lists were …
> Improved Commands and List

- provider/huggingchat.py
Huggingchat team [implemented](https://huggingface.co/spaces/huggingchat/chat-ui/commit/b9f029bdc3e9b74565b7102787a1466aa75471ea) a check for API calls. Now you need to accept an ethical modal before initiating conversations.
Altered the instruct method on the provider and ran it directly through terminal.
> Fix huggingchat provider

- commands/file_operations.py
- frontend/components/systems/provider/ProviderList.js
- provider/gpt4free.py
- provider/huggingface.py
- requirements.txt
and fix provider listing in frontend
Add some pythons classses and changed a javascript file.
More llm provider are better.
> Add gpt4free and huggingface provider

- Dockerfile-backend
Improves dockerfile for the agent backend.
I had issues to open files, which are created by the agent.
The docker image ran as root user,
so it created files with root permission.
> Improve dockerfile / fix file permission issue

- .env.example
- Config/__init__.py
- commands/file_operations.py
- provider/huggingchat.py
While running the agentllm via command line, i detected some problemns regarding file_operations methods:
1) Method `safe_join` needed an envar that was not defined. I added it to `.env.example and to `Config.__init__`.
2) Method `safe_join` could not resolve correctly `os.path.join` when `paths` began with a "/". If so, it would only consider paths and ignore `base` parameter. 
Details can be seen here:
"[If a component is an absolute path, all previous components are thrown away and joining continues from the absolute path component.](https://docs.python.org/3/library/os.path.html#os.path.join)"
3) Converted all methods from `file_operations` to static methods. Previously, when running the agent via command line, it was returning errors everytime a method from `file_operations`, since …
> Fix methods on commands.file_operations

- AgentLLM.py
- Commands.py
- app.py
- commands/chain_commands.py
- commands/work_with_ai.py
- docker-compose-mac.yml
- docker-compose.yml
- docs/README.md
- model-prompts/bard/execute.txt
- model-prompts/bard/instruct.txt
- model-prompts/chatgpt/execute.txt
- model-prompts/chatgpt/instruct.txt
- model-prompts/default/execute.txt
- model-prompts/default/instruct.txt
- model-prompts/gpt-3.5-turbo/execute.txt
- model-prompts/gpt-3.5-turbo/instruct.txt
- model-prompts/gpt-4/execute.txt
- model-prompts/gpt-4/instruct.txt
- model-prompts/openassistant/execute.txt
- model-prompts/openassistant/instruct.txt
- model-prompts/vicuna/execute.txt
- model-prompts/vicuna/instruct.txt
- prompts/Execution.txt
- prompts/Instruction.txt
- Switch format for responses to JSON with @lgwacker method in #243 
- Updated prompting for instruct and execute so that commands are returned with json.
> Instruct/Execute format for responses to JSON, Fix docker-compose, remove old refs.

- provider/bard.py
- provider/chatgpt.py
- provider/fastchat.py
- provider/huggingchat.py
- provider/huggingface.py
- provider/kobold.py
- provider/llamacpp.py
- provider/oobabooga.py
Adding AI_MODEL per provider to be used for choosing the `model-prompts` for the task objectives and instruct.
> Add AI_MODEL flat per provider

- Chain.py
- chains/README.md
- Updated documentation with basic example
- Added the ability to run a chain straight from Chain.py with command line.
```
python3 Chain.py --chain "Generate Cat Jokes"
```
> Run chain with command line

- AgentLLM.py
> Prevents error from happening if key 'commands' not in self.response

- docs/providers/BING.md
- provider/bing.py
- requirements-mac.txt
- requirements.txt
> Add Bing Provider

- AgentLLM.py
- Memories.py
> Set limit to 128

- AgentLLM.py
- Config/Agent.py
- Memories.py
- app.py
- provider/gpt4free.py
- provider/oobabooga.py
- Move spacy to Memories
- Fix type errors with ooba provider
- Remove gpt4free max_tokens requirement
> Move spacy to Memories, Fix type errors with ooba provider, Remove gpt4free max_tokens requirement

- provider/huggingchat.py
Removing token ceiling on Huggingchat, causing issues.
> Removing token ceiling on Huggingchat, causing issues.

- API-Tests.ipynb
- Config/Agent.py
- Memories.py
- provider/chatgpt.py
- requirements-mac.txt
- requirements.txt
Chatgpt Rework, Agent Memory Hotfixes
> Chatgpt Rework, Agent Memory Hotfixes

- AgentLLM.py
- Config/Agent.py
- Memories.py
> Memories Hotfix

- docs/providers/CHATGPT.md
- provider/chatgpt.py
Switch to ChatGPT Token from username and password, updated docs.
> Switch to ChatGPT Token from username and password

- provider/bing.py
Adding styles based on temp for Bing
> Adding styles based on temp for Bing

- provider/bard.py
- provider/bing.py
Move chatbot to init for Bard and Bing
> Move chatbot to init for Bard and Bing

- Dockerfile-backend-nvidia
- Dockerfile-fastchat
- docker-compose-fastchat.yml
- provider/gpt4all.py
- provider/gpt4allgpu.py
- requirements-mac.txt
- requirements.txt
> Add gpt4all from #227

- AgentLLM.py
Add None option for tasks list.
> Add None option for tasks list.

- provider/llamacpp.py
- requirements-mac.txt
- requirements.txt
Switch to better working llamacpp provider
> Switch to better working llamacpp provider

- provider/openai.py
> Fix openai max tokens

- provider/llamacpp.py
> Set max tokens for llamacpp

- provider/palm.py
- requirements.txt
> Add Palm Provider

- AgentLLM.py
Extract JSON from output
This new method extracts the first JSON between braces { } if there is one in output
Update the validate_json function
With some models outputs are not 100% a JSON object like : 
<< Here is your output : { .... } >>
Those are seen as INVALID JSON RESPONSE.
VIcuna-1.1 and oobabooga
- [] **Bug fix** (prefix: `fix` - non-breaking change which fixes an issue)
- [x ] **New feature** (prefix: `feat` - non-breaking change which adds functionality)
> Extract JSON from output

- AgentLLM.py
import regex was needed to JSON extract to function
> Correct missing import regex

- AgentLLM.py
- Config/Agent.py
> Force default model if empty

- commands/google.py
- commands/web_selenium.py
> Add staticmethod to commands that don't share state

- AgentLLM.py
> Fix json validation

- model-prompts/starchat/execute.txt
- model-prompts/starchat/instruct.txt
- model-prompts/starchat/priority.txt
- model-prompts/starchat/task.txt
- model-prompts/starchat/validate.txt
- provider/huggingface.py
- Huggingface Transformers modifications for `max_new_tokens` and setting default to Starchat.  
- Created Starchat prompts.
> Huggingface Transformers modifications

- docs/providers/LLAMACPP.md
- provider/llamacpp.py
add basic pre-test if model exists locally
update documentation how to run llamaCPP
Running a llama model locally on CPU for general setup test purpose and ran into errors.
Wrong directory silently fails now. Thus there is nothing to test.
Improvements can be added, text will be updated.
- [? yarn falis for me?] My code follows the code style of this project and passes `yarn run lint`.
> Improve error handling for llamaCPP

- .gitbook.yaml
- docs/providers/BARD.md
- docs/providers/BING.md
- docs/providers/FASTCHAT.md
- docs/providers/GPT4ALL.md
- docs/providers/GPT4FREE.md
- docs/providers/GPUGPT4ALL.md
- docs/providers/HUGGINGCHAT.md
- docs/providers/KOBOLD.md
- docs/providers/LLAMACPP.md
- docs/providers/OOBABOOGA.md
- docs/providers/OPENAI.md
- docs/providers/PALM.md
- provider/llamacpp.py
- Added an Agent-LLM space on gitbook.io
- Set up sync from this repo&branch
- invited @Josh-XT as admin (needs only two steps to autogenerate from main repo)
- result here https://agent-llm.gitbook.io/docs/readme
clicking MD files on github isn't that cool.
Added value: afaik, docs can be edited on gitbook page and replayed as a PR on github.
Space is set up to github over gitbook (so syncs go always for the source code)
https://agent-llm.gitbook.io/docs/readme
- [] My change requires a change to the documentation.
> Enable gitbook for easier access of docs

- AgentLLM.py
- app.py
- commands/web_selenium.py
- prompts/WebSearch.txt
- smarterchat.py
Add SmarterChat - Web searching/scraping learning agent.
> Add SmarterChat - Web searching/scraping learning agent

- API-Tests.ipynb
- AgentLLM.py
- Config/Agent.py
- Embedding.py
- Memories.py
- app.py
- requirements.txt
- Add Embedding Provider Concept
- Chunk sizes determined by embedding provider for all memory for both storage and retrieval based on chosen embedding provider.
> Add Embedding Provider Concept

- .github/workflows/python-publish.yml
Workflow pipeline quickfix for https://github.com/Josh-XT/Agent-LLM/pull/317
local checks don't check the github pipeline
smart review ;P
- [?] My change works!
> add missing gitbook plugin installation for docs

- docker-compose-linux-arm64.yml
- docs/README.md
> Add Linux Arm64 Support Docker & Updated readme for the documentation

- AgentLLM.py
- Config/Agent.py
- prompts/SmartChat-Researcher.txt
- prompts/SmartChat-Resolver.txt
- prompts/SmartChat-StepByStep.txt
- prompts/SmartInstruct-Researcher.txt
- prompts/SmartInstruct-Resolver.txt
- prompts/SmartInstruct-StepByStep.txt
- prompts/WebSearch.txt
- Reworked task system
- Removed prioritization agent, no value.
- Task creation agent is now one line inside of the `run_task` function
- Execution agent has been replaced by Smart Instruct.
These changes will make the task system far more intelligent through multiple shots and validation, but will also take significantly longer.  Tasks will be done more accurately at the cost of time, and money if using a model that costs money.
> Reworked Task System for Smart Tasks

- AgentLLM.py
- commands/web_selenium.py
- prompts/WebSearch.txt
- requirements.txt
> Websearch fix

- provider/gpt4free.py
> Gpt4free hotfix

- docs/README.md
> Quick Fix Formatting Readme

- AgentLLM.py
Fix smart functions, switch search to playwright
> Fix smart functions, switch search to playwright

- .github/workflows/operation-docker-build-publish.yml
> Workflow testing

- Dockerfile-streamlit
> Upgrade Packages ensure fix Arm64

- provider/gpt4free.py
Potentially better GPT4Free.  It constantly loops through the providers of GPT4free until it gets a response.
> Better gpt4free?

- streamlit.py
> Fix Streamlit Status and Move it to the side 

- AgentLLM.py
- streamlit.py
Update run task with async option
> Update run task with async option

- docs/3-Providers/Azure OpenAI.md
- provider/azure.py
> Add Azure OpenAI Provider

- AgentLLM.py
- Memories.py
- requirements.txt
- streamlit.py
- Add Read file to memory
- Fix memory chunking issue
- Add Upload file to Streamlit Chat page.
> Add Read file to memory

- .github/workflows/publish-docker.yml
please make sure follwowing exists:
username: ${{ vars.DOCKERHUB_USERNAME }}
password: ${{ secrets.DOCKERHUB_TOKEN }}
ITS VARS NOW (same settings, different tab)
make everything work
> Tweak docker chaining

- .github/workflows/publish-docker.yml
> running on pushes to main and also manually

- .github/workflows/publish-docker.yml
> fix secrets transfer

- .github/workflows/publish-docker.yml
> fix run behaviour

- .github/workflows/publish-docker.yml
- docker-compose.yml
- docs/README.md
> introducing profiles for docker compose

- docker-compose.yml
Fixes the issue that you can't access the server.
> Docker Port Correction Fix

- AgentLLM.py
Sometimes app crashes when commands is not well formated,
_command_name, command_args in validated_response["commands"].items():
TypeError: 'bool' object is not subscriptable_
Sometimes app crashes when commands is not well formated:
for example (even with a null output)
So the app doesn't crash
Oobabooga Agent
> fix validated_response["commands"].items(): TypeError

- docker-compose.yml
- docs/README.md
> Fix compose docs and add profile "all"

- docs/README.md
Include Instructions For Using PipReqs to Update & Install
Requirements Spawning From Extending or Modifying Files.
> Updated "Extending Functionality"

- requirements.txt
Didn't test but I assume this should fix this problem.
> Add ffmpeg fix RuntimeWarning

- docker/Dockerfile
> arm64: fixing dependency libgomp1 - will automatically install on upgrade

- AgentLLM.py
Don't browse a site already seen in this session.
> Don't browse a site already seen in this session.

- provider/huggingchat.py
- requirements.txt
Switch to using hugchat module for HuggingChat Provider.
```
pip install hugchat
```
> Switch to using hugchat module for HuggingChat Provider.

- commands/file_operations.py
> Fix file error in #326

- docker/Dockerfile
- docker/Dockerfile.nvidia
- docker/Dockerfile.streamlit
> Add ffmpeg to Docker fix runtime error

- docker/Dockerfile.streamlit
> Hopfully fixes the libgomp runtime error this time 🤞

- src/agixt/AGiXT.py
- src/agixt/Chain.py
- src/agixt/Commands.py
Reworked run_chain_step and moved it from `AGiXT.py` to `Chain.py` for clearer separation in classes.
- Prompt
- Command
- Chain
- Smart Instruct
- Smart Chat
- Task
> Chain modifications

- src/agixt/pages/Custom Prompts.py
- src/agixt/pages/Instructions.py
Fix Custom Prompts and Instructions in Streamlit
> Fix Custom Prompts and Instructions in Streamlit

- src/agixt/provider/gpt4free.py
deepai default got gpt4free
- Set loop to deepai, useless, then you.
> deepai default got gpt4free

- src/agixt/pages/Tasks.py
> Fix Dupe Tasks Field

- src/agixt/pages/Profile.py
- src/agixt/pages/Tasks.py
> Add Login Redirect To Profile Page

- docs/3-Providers/Anthropic Claude.md
- src/agixt/provider/claude.py
- src/agixt/requirements.txt
> Add Anthropic Claude Provider

- src/agixt/auth_libs/Users.py
- src/agixt/pages/Agent_Settings.py
- src/agixt/pages/Chains.py
- src/agixt/pages/Chat.py
- src/agixt/pages/Custom_Prompts.py
- src/agixt/pages/Instructions.py
- src/agixt/pages/Login.py
- src/agixt/pages/Profile.py
- src/agixt/pages/Tasks.py
Removes a lot of unnecessary duplicated code.
> Add check_auth_status

- docker/docker-compose-mac-streamlit.yml
- docker/docker-compose-mac.yml
- docker/docker-compose.yml
Deleted .env references in docker-compose yml files, since it is not needed anymore.
All .env references were deleted from the code
deleted and repulled the changed containers
> Deleted .env references in docker-compose files

- agixt/requirements.txt
Missing in requirements
add bcrypt into requirements.txt
to reduce the errors
added manualy, error is gone
> add bcrypt

- agixt/provider/chatgpt.py
- agixt/requirements.txt
- docs/3-Providers/ChatGPT.md
It appears that the `revChatGPT` module has the ChatGPT Provider working again. 
https://github.com/acheong08/ChatGPT
> Add ChatGPT Provider

- agixt/provider/llamacpp.py
Updated to latest version of the llamacpp python package and added the new feature flags as agent settings.
> Llamacpp Provider Improvements

- agixt/provider/gpt4all.py
- agixt/provider/gpugpt4all.py
- agixt/provider/llamacpp.py
- agixt/provider/transformer.py
- agixt/requirements.txt
> Clean up base requirements

- agixt/auth_libs/Redirect.py
> Fix typo in Redirect.py

- agixt/API-Tests.ipynb
- agixt/Agent.py
- agixt/Embedding.py
- agixt/Memories.py
- agixt/app.py
- agixt/pages/0-Agent_Settings.py
- agixt/requirements.txt
Fix agent_settings in fastapi as well as several other issues with agent settings and embedding.
> Fix agent_settings from fastapi

- agixt/Agent.py
Agent command list will automatically update with what is available from AGiXT so that when new command extensions are added, agent configs will now update automatically adding those as `disabled` for that agent, but giving the user the ability to enable them in the agent settings.
> Dynamic Agent Commands.

- .github/workflows/publish-docker.yml
- .github/workflows/publish-python.yml
- Dockerfile
- docker-compose.yml
The build pipeline updates. Please review.
If any questions, i'd deliver fixes.
When it's merged, i will double check everything works from inside original AGIXT repo
Just send me pipeline runs or any errors after this is upstream.
> updates build pipeline

- agixt/Commands.py
- agixt/app.py
> some loggings

- agixt/provider/huggingface.py
Add huggingface provider for #475
> Add huggingface provider for #475

- agixt/AGiXT.py
- agixt/Memories.py
- agixt/commands/file_operations.py
- agixt/commands/web_requests.py
Fixed File Commands.
Modified File Commands To Properly Pass Values
Agents would pass variables incorrectly before, when attempting to utilize FIle Commands.
Potential Issue Fix: https://github.com/Josh-XT/AGiXT/issues/471
Multiple Tasks Requiring Reading, Writing, Finding, Appending to Files.
> Fix File Commands

- agixt/commands/audio_text.py
- agixt/commands/execute_code.py
- agixt/commands/github.py
- agixt/commands/image_generator.py
Add working directory in commands that use files operations
Add the working directory in the commands : `audio_text`,  `execute_code`, `github` and `image_generator` as a default parameter in the init function as in the `file_operation` command
If an agent clone a github rep and want work in it it as to be in the Working directory
> Add working directory as a default location for commands that use files

- .github/workflows/publish-docker.yml
- disable dockerhub on PRs - prevent fails and allow build
- re-enable arm64 arch
> enable arm64 on docker builds, fix PR build behaviour

- agixt/commands/google.py
Remove DDG from google search module
> Remove DDG from google search module

- agixt/commands/searxng_commands.py
> Fix and test SearXNG Search

- agixt/AGiXT.py
- agixt/Chain.py
- agixt/Prompts.py
- agixt/__init__.py
- agixt/app.py
- agixt/pages/5-Chains.py
- agixt/pages/6-Prompts.py
- docs/2-Concepts/Prompts.md
Custom Prompts to Prompts - name seemed ambiguous.
> Custom Prompts to Prompts

- agixt/pages/1-Learning.py
> Add await to learning

- agixt/provider/kobold.py
> update kobold provider

- tests/quickchecks.ipynb
Cleanup testfile and add assertions into tests
> Tests update

- docs/README.md
`cd` into the cloned directory in README.
The README instructions lacked `cd`ing into the cloned directory.
This PR fixes this.
By executing it in a local shell.
> Make README instructions copy&paste ready

- agixt/AGiXT.py
> Fix bad return on execution agent

- agixt/AGiXT.py
- agixt/prompts/Execution.txt
- agixt/prompts/Instruction.txt
- agixt/prompts/SmartInstruct-CleanResponse.txt
- agixt/prompts/SmartTask-CleanResponse.txt
- agixt/prompts/Validation.txt
- agixt/prompts/ValidationFailed.txt
- agixt/prompts/gpt-3.5-turbo/instruct.txt
- agixt/prompts/gpt-4/instruct.txt
- agixt/prompts/instruct.txt
- agixt/prompts/starchat/instruct.txt
- agixt/prompts/vicuna/instruct.txt
Update command validation and prompts
> Update command validation and prompts

- agixt/AGiXT.py
Change command_name as friendly_name in AGITX.py to success the check in the find_command function in Extension.py
> Command execution fix

- agixt/AGiXT.py
- agixt/provider/runpod.py
- agixt/provider/runpodAPI.py
Provider for runpod's serverless API-endpoints.
I would like to test it and finetune it together with @Josh-XT , e.g. make sure the performance is the one expected, clear some output etc.
Have models on demand
Like this - tested (:tm:)
I'm not really sure why all the phantasy...maybe we need to tune parameters. I've never talked to any AI about podcasting (urgh) and wiped memories of this agent beforehand. All i sent was "Hi"
> threaded provider for runpod

- docs/1-Getting started/Quick Start.md
> Update Quick Start.md

- agixt/Chain.py
- agixt/Memories.py
- pyproject.toml
Fix step replacement in Chains
> Fix step replacement in Chains

- agixt/AGiXT.py
- agixt/Chain.py
- agixt/chains/Write a Poem_responses.json
> Fix chain step replacement

- agixt/pages/3-Chains.py
> Fix modify chain step

- agixt/AGiXT.py
Fix command execution in instruct
> Fix command execution in instruct

- docker-compose.yml
> Fix mount paths in docker-compose.yml

- agixt/Memories.py
- agixt/provider/llamacpp.py
- docs/README.md
Update llamacpp, fix memory issue, update doc
> Update llamacpp, fix memory issue, update doc

- agixt/provider/llamacppapi.py
> Update llamacpp api provider for #539

- agixt/Chain.py
> Add move_step for chain steps

- agixt/app.py
Implicit definitions in app.py to make sure variables are where they're supposed to be.
> Implicit definitions in app.py

- agixt/app.py
loading a chain seems to throw an exception in the inner world of agixt, when the chain name finds no match.
We catch this and return 404
This means also other errors like a total unavailability of agixt will result in 404 - but should in 500.
Due to the latter has fewer cases in reality, we wrap it to 404 on the get endpoint.
> return 404 when chain is not found

- agixt/Agent.py
- agixt/ApiClient.py
- agixt/Chain.py
- agixt/Extensions.py
- agixt/Tasks.py
- agixt/app.py
- agixt/chains/Write a Poem.json
- agixt/chains/Write a Poem_responses.json
- agixt/components/agent_selector.py
- agixt/pages/0-Agent_Settings.py
- agixt/pages/1-Learning.py
- agixt/pages/2-Prompts.py
- agixt/pages/3-Chains.py
- agixt/pages/4-Chat.py
- agixt/pages/5-Instructions.py
- agixt/pages/6-Tasks.py
- agixt/provider/__init__.py
- agixt/tests.ipynb
Migration to Streamlit using FastAPI
> Migration to Streamlit using FastAPI

- agixt/pages/6-Tasks.py
> Fix get tasks

- agixt/Extensions.py
> Fix bad ref

- agixt/Agent.py
- agixt/ApiClient.py
- agixt/Config.py
- agixt/app.py
- agixt/tests.ipynb
> Fix agent settings

- Dockerfile
- docs/README.md
Update Readme to latest poetry version, 1.5.0 has some bugs hitting in here
https://github.com/Josh-XT/AGiXT/pull/567
> Update docs, update poetry version

- .github/workflows/operation-docker-build-publish.yml
- .github/workflows/operation-python-build-publish.yml
- .github/workflows/operation-test-with-jupyter.yml
- .github/workflows/publish-docker.yml
- .github/workflows/publish-python.yml
- .github/workflows/test-ai-suite.yaml
- agixt/AGiXT.py
- pyproject.toml
- tests/quickchecks.ipynb
Implicit definitions, Bug Fixes, Workflows
> Implicit definitions, Bug Fixes, Workflows

- docs/2-Concepts/Agents.md
- docs/README.md
> Docs updates to fix #509 and #531

- agixt/Config.py
- agixt/pages/0-Agent_Settings.py
- agixt/tests.ipynb
Fix Agent Settings and Agent List
> Fix Agent Settings and Agent List

- agixt/pages/0-Agent_Settings.py
Fix formatting in Agent Settings
> Fix formatting in Agent Settings

- agixt/pages/4-Chat.py
- agixt/pages/5-Instructions.py
- agixt/tests.ipynb
> Implicit defs

- agixt/pages/4-Chat.py
- agixt/pages/5-Instructions.py
Fix chat entries
- Replaced `sender` with `role` and `Agent` with the agent's name.
> Fix chat entries

- agixt/Chain.py
- agixt/app.py
- Add workers arg to app.py
- Remove old ref
> Add workers arg to app.py

- agixt/pages/4-Chat.py
- agixt/pages/5-Instructions.py
> Fix chat history

- run-linux-konsole.sh
*should* work with xterm, no promises.
> Added Konsole run

- agixt/pages/4-Chat.py
- agixt/pages/5-Instructions.py
> Another attempt to fix chat history.

- docs/README.md
updated readme
make it easier for ppl without programming experience
did it myself
> update readme, remove dublication, add go to folder

- agixt/AGiXT.py
- agixt/Agent.py
- agixt/provider/azure.py
- agixt/provider/bard.py
- agixt/provider/bing.py
- agixt/provider/chatgpt.py
- agixt/provider/claude.py
- agixt/provider/fastchat.py
- agixt/provider/gpt4all.py
- agixt/provider/gpt4free.py
- agixt/provider/gpugpt4all.py
- agixt/provider/huggingchat.py
- agixt/provider/huggingface.py
- agixt/provider/kobold.py
- agixt/provider/llamacpp.py
- agixt/provider/llamacppapi.py
- agixt/provider/oobabooga.py
- agixt/provider/openai.py
- agixt/provider/palm.py
- agixt/provider/runpod.py
- agixt/provider/transformer.py
- agixt/tests.ipynb
Switch providers instruct to async
> Switch providers instruct to async

- poetry.lock
- pyproject.toml
> Add ffmpeg to fix #530

- agixt/Agent.py
> Fix commands prompting

- agixt/AGiXT.py
- agixt/Extensions.py
Command execution modifications and testing
> Command execution modifications and testing

- agixt/provider/llamacppapi.py
> Fix #539 for llamacpp API provider

- docs/1-Getting started/Quick Start.md
- docs/3-Providers/FastChat.md
- docs/3-Providers/GPT4ALL-GPU.md
- docs/3-Providers/GPT4ALL.md
- docs/3-Providers/Hugging Face Transformers.md
- docs/3-Providers/Kobold.md
- docs/3-Providers/Oobabooga Text Generation Web UI.md
- docs/3-Providers/llamacpp API.md
- docs/3-Providers/llamacpp.md
- docs/README.md
Improved documentation in several places and corrected old references.
> Documentation Improvements

- .streamlit/config.toml
- agixt/.streamlit/config.toml
> Add Darker Theme and set it to default theme

- Dockerfile
- agixt/Agent.py
- agixt/Extensions.py
- docker-compose.yml
Fix Dockerfile and Docker-Compose
> Fix Dockerfile and Docker-Compose

- agixt/Agent.py
Chat history to history.yaml in agent folder
> Chat history to history.yaml in agent folder

- agixt/Agent.py
- agixt/Extensions.py
Fix naming refs to yaml history
> Fix naming refs to yaml history

- agixt/AGiXT.py
- Clean up command validation
- Increases the speed of command execution by cutting out a validation step unless there is an error.
> Clean up command validation

- agixt/AGiXT.py
> Fix validation agent return.

- agixt/Agent.py
- agixt/tests.ipynb
> Fix agent rename

- agixt/pages/0-Agent_Settings.py
- agixt/pages/1-Learning.py
- agixt/pages/2-Prompts.py
- agixt/pages/3-Chains.py
- agixt/pages/4-Chat.py
- agixt/pages/5-Instructions.py
- agixt/pages/6-Tasks.py
- agixt/pages/Login.py
- agixt/pages/Profile.py
- agixt/pages/Register.py
> [Streamlit] Update Chat and Add Favicons to pages (readd 😄 )

- agixt/provider/gpt4free.py
> Remove theb from gpt4free

- agixt/Agent.py
- agixt/provider/gpt4free.py
- agixt/tests.ipynb
> Fix gpt4free rotation

- streamlit/pages/6-Tasks.py
> Update task buttons

- agixt/AGiXT.py
Smart Instruct modification to execution
> Smart Instruct modification to execution

- agixt/prompts/Tell Me How.txt
- streamlit/pages/7-Prompt Agent.py
> Add Prompt Agent page

- docs/2-Concepts/Chains.md
- docs/2-Concepts/Prompts.md
- streamlit/pages/2-Prompts.py
- streamlit/pages/7-Prompt Agent.py
> Update prompt template docs

- docs/README.md
> update logo img in docs

- streamlit/Main.py
> update for img for Main.py

- streamlit/Main.py
- streamlit/components/docs.py
- streamlit/pages/0-Agent_Settings.py
- streamlit/pages/1-Prompt_Templates.py
- streamlit/pages/2-Chain_Management.py
- streamlit/pages/3-Interact.py
- streamlit/pages/6-Tasks.py
Streamlit UX Improvements
- Added quick links to all pages for the documentation, GitHub, Discord, and Twitter.
- Moved usage information on `Prompt Templates` and `Chain Management` pages to under the inputs.
> Streamlit UX Improvements

- agixt/Chain.py
- streamlit/pages/0-Agent_Settings.py
- streamlit/pages/2-Chain_Management.py
Streamlit Caching for better performance
- Added caching to Agent Settings and Chain Management pages.  Still some work to do, but performance is significantly better.
> Streamlit Caching for better performance

- streamlit/pages/3-Interact.py
> Add Enter button functionality chat for send msg

- agixt/chains/Smart Instruct.json
- agixt/prompts/SmartChat-Resolver.txt
- agixt/prompts/SmartInstruct-Resolver.txt
Smart Chains
- Smart Chat and Smart Instruct converted to Chains.
> Smart Chains

- agixt/chains/Smart Chat.json
- agixt/chains/Smart Instruct.json
- agixt/chains/Task.json
- agixt/extensions/agixt_agent.py
- streamlit/pages/2-Chain_Management.py
> Fix agent name refs

- pyproject.toml
> v1.2.1-beta

- streamlit/pages/0-Agent_Settings.py
- streamlit/pages/3-Interact.py
Fix chat history error and Agent Settings
> Fix chat history error and Agent Settings

- poetry.lock
- pyproject.toml
- streamlit/components/history.py
- streamlit/pages/2-Chain_Management.py
- streamlit/pages/3-Interact.py
> Add Agent History

- agixt/Agent.py
> Add timestamp to history

- requirements.txt
> Add ffmpeg to requirements

- docker-compose.dev.yaml
- docker-compose.yml
Add `UVICORN_WORKERS` environment variable to allow people to choose how far to scale uvicorn workers.
> Add Uvicorn workers

- AGiXT.sh
> make script so much better :D

- streamlit/components/verify_backend.py
Rerun front end page if it launches back end.
> Rerun front end if it launches back end

- agixt/Agent.py
- agixt/provider/gpt4free.py
Readd provider request logging
> Improve gpt4free error handling

- requirements.txt
- streamlit/Main.py
> Fix first launch streamlit to load backend correctly

- streamlit/Main.py
> quick fix st.config error

- agixt/Chain.py
- agixt/app.py
- streamlit/ApiClient.py
- tests/ApiClient.py
- tests/tests.ipynb
```
{
"1": {
"response": "Quantum computers, a marvel of science,\nRevolutionizing our computing reliance.\nThey operate not with bits but with qubits,\nEncoding data with quantum bits!\n\nQuantum computers can solve problems immense,\nThat classical computers struggle to make any sense.\nTheir calculations faster than light,\nAble to work with incredible might!\n\nParallel processing is quantum's forte,\nIt can work on multiple tasks all day.\nPrivacy isn't a problem, not at all,\nQuantum encryption is nigh impossible to breach, for all!\n\nQuantum computers, a technology new,\nA future filled with promise for me and you.\nThe limits are endless, the sky's the limit,\nIt's a technological revolution, baby, embrace it!",
"agent_name": "new_agent",
"prompt": {
"prompt_name": "Write a …
```
> Revamp chain responses

- streamlit/pages/2-Chain_Management.py
- Add Chain to Step Types, you can now add a Chain as a step of another Chain, including running a chain in an infinite loop.
- Fix add chain step
> Add Chain to Step Types in Chains, Fix add chain step

- AGiXT.sh
> Add Docker update to script and edit entries in menu

- agixt/Agent.py
- agixt/app.py
- streamlit/ApiClient.py
- tests/ApiClient.py
Add delete_history_message
Usage:
`ApiClient.delete_history_message(agent_name=agent_name, message="the message that needs deleted")`
> Add delete_history_message

- AGiXT.sh
Add step to start back end before front end in AGiXT.sh
> Add step to start back end before front end in AGiXT.sh

- streamlit/components/learning.py
- streamlit/pages/3-Interact.py
> Fix some python errors

- streamlit/components/selectors.py
- streamlit/pages/2-Chain_Management.py
> Chain ref cleanups

- agixt/Agent.py
- agixt/Chain.py
- agixt/Interactions.py
- agixt/Memories.py
- agixt/Prompts.py
- agixt/app.py
- streamlit/pages/3-Interact.py
- tests/tests.ipynb
- Many security updates
- Enabled CodeQL to scan for security vulnerabilities and took the recommendations to fix all of them in this PR.
> Security updates

- agixt/provider/gpt4free.py
- requirements.txt
- tests/tests.ipynb
Update cryptography and gpt4free
> Update cryptography and gpt4free

- agixt/extensions/agixt_agent.py
> Fix prompt_agent

- agixt/extensions/agixt_agent.py
- requirements.txt
"Describe Image" command using FuseCap has been added as part of the work for #649 .
> Describe Image command

- agixt/Chain.py
- streamlit/components/selectors.py
> Fix chain execution

- agixt/extensions/agixt_agent.py
> Move initialization out of loop

- agixt/provider/poe.py
> Move Poe Init

- agixt/extensions/agixt_agent.py
> Fix bad ref to prompt args

- agixt/Interactions.py
- agixt/chains/Smart Chat.json
- agixt/chains/Smart Instruct.json
- agixt/chains/Task.json
- agixt/extensions/agixt_agent.py
- agixt/prompts/Custom Input.txt
- agixt/prompts/Get Task Description.txt
- Giving the AI the ability to **create and run new chains** populating each step with a task from the initial generated list of tasks based on the user's input.
- Added multi-shot prompts to the `run` function.
- Modified Smart Chat and Smart Instruct chains.
> AI Generated Task Chains, Multi-Shot Prompts in Chains

- agixt/chains/Smart Task.json
- agixt/extensions/agixt_agent.py
> AI Generated Smart Tasks

- streamlit/pages/2-Chain_Management.py
- streamlit/pages/3-Interact.py
> add area input for interact and Chains mngmt

- agixt/chains/Generate Smart Task Chain.json
- agixt/chains/Generate Task Chain.json
- agixt/chains/Generate and Run Smart Task Chain.json
- agixt/chains/Generate and Run Task Chain.json
Task Chain Updates
- Added renamed "Task" and "Smart Task" chains and added 2 additional chains.
New chains are:
- Generate Task Chain
- Generate and Run Task Chain
- Generate Smart Task Chain
- Generate and Run Smart Task Chain
> Task Chain Updates

- agixt/extensions/agixt_agent.py
Increase range for numbered list of tasks.
- Change from 10 to the length of the task list.
> Increase range for numbered list of tasks.

- agixt/Interactions.py
Add option for `all_responses` to `run_chain`.
- It is default to `True` so that there will be no unexpected behaviors, but I believe it will be useful to have the option.
- If set to `False`, the chain will return only the last response from the chain.  This is more optimal for running a chain inside of another chain for step replacements.
> Add option for all_responses to run_chain.

- agixt/Agent.py
> Fix history

- agixt/app.py
- streamlit/components/learning.py
Fix #703 learn from file issue
> Fix #703 learn from file issue

- agixt/Embedding.py
> Increase Ada Max Tokens

- agixt/provider/gpt4free.py
Remove Poe from gpt4free rotation to prevent crash.
> Remove Poe from gpt4free rotation to prevent crash

- agixt/Interactions.py
- agixt/chains/Generate and Run Smart Task Chain.json
- agixt/chains/Generate and Run Task Chain.json
- agixt/extensions/agixt_chain.py
Fix running chains inside of chains
> Fix running chains inside of chains

- agixt/chains/Generate Smart Task Chain without Research.json
- agixt/chains/Generate Smart Task Chain.json
- agixt/chains/Generate Task Chain without Research.json
- agixt/chains/Generate Task Chain.json
- agixt/chains/Generate and Run Smart Task Chain.json
- agixt/chains/Generate and Run Task Chain.json
- agixt/extensions/agixt_chain.py
- agixt/prompts/Title a Chain.txt
To avoid duplicates and length issues fix generated chain files, I suggest some changes to how they are named.    
Also, for future change, ideally, these generated chains should be stored in their own folder, inside the chains folder.
duplicates and length issues
- [ x] **New feature** (prefix: `feat` - non-breaking change which adds functionality)
- [ x] **Refactor** (prefix: `refactor` - non-breaking change which only improves the design or structure of existing code, and making no changes to its external behaviour)
- [ x] My code follows the code style of this project and passes `yarn run lint`.
- [x ] My change works!
> Change AI Generated Chains naming approach to use a five-word summary of the initial prompt + a timestamp 

- agixt/extensions/agixt_chain.py
- agixt/prompts/Task Execution.txt
> Fix bad chain refs

- agixt/chains/Generate Smart Task Chain without Research.json
- agixt/chains/Generate Smart Task Chain.json
- agixt/chains/Generate Task Chain without Research.json
- agixt/chains/Generate Task Chain.json
- agixt/chains/Generate and Run Smart Task Chain.json
- agixt/chains/Generate and Run Task Chain.json
> Fix task chains

- Dockerfile
Update docker playwright install to use npx as recommended by Microsoft.
> Update docker playwright install to use npx

- agixt/Interactions.py
> Force int for shots

- agixt/Interactions.py
- agixt/app.py
- streamlit/ApiClient.py
- streamlit/pages/3-Interact.py
- tests/ApiClient.py
Add Chain Agent override
- Ability to override the Agent set per step with one selected at the time of running the chain.
> Add Chain Agent override

- agixt/Agent.py
- agixt/app.py
- streamlit/ApiClient.py
- streamlit/pages/0-Agent_Settings.py
- tests/ApiClient.py
Feature: Import Agent Settings
- Ability has been added to import agent configuration files so that you can easily copy your agent configuration to another devices or share them.  Please note that these config files have API keys in them for some providers, make sure to not share your API keys!
> Feature: Import Agent Settings

- agixt/Chain.py
- agixt/app.py
- streamlit/ApiClient.py
- streamlit/pages/2-Chain_Management.py
- tests/ApiClient.py
Feature: Import Chains
- Share your chains with friends with the `Export Chain` feature and import those chains to run them with the new `Import Chain` feature.
> Feature: Import Chains

- agixt/app.py
Add endpoints for completions like OpenAI's
- See issue #643 
- https://platform.openai.com/docs/api-reference/chat/create
- https://platform.openai.com/docs/api-reference/completions/create
> Add endpoints for completions like OpenAI's

- agixt/chains/Solve Math Problem.json
- agixt/extensions/agixt_agent.py
- agixt/prompts/Create New Command.txt
- agixt/prompts/Translate Math to Python.txt
- This prompt will inform the AI that it is not good at math, but is very good at Python, and having it translate the math problem it has been presented to Python code.
- So far having pretty good results with GPT3.5 and GPT4.
- Takes an AI response and strips out anything in a markdown code block for Python, saves the code to a `temp.py` file in the `WORKSPACE` directory.
- Executes the Python script that it created.
- Deletes script once execution is complete, then returns the response from the script.
- Two step reusable chain
- Uses new prompt `Translate Math to Python` in Step 1 taking the math problem as the user input, then passes the response to the new command `Execute Python Code` to get the answer.
> New Command: Execute Python Code, New Chain: Solve Math Problem

- agixt/extensions/agixt_agent.py
- agixt/extensions/agixt_chain.py
- agixt/extensions/file_system.py
- agixt/prompts/Convert OpenAPI Endpoint.txt
- agixt/prompts/Get ezsession Auth Type.txt
- agixt/prompts/Get ezsession Function.txt
- agixt/prompts/New Extension Format.txt
Work towards autonomous extension generation.
> OpenAPI to Extension Commands

- agixt/Interactions.py
> Improve websearch in chains

- agixt/Interactions.py
step_response Bugfix in run chain.
> step_response Bugfix in run chain.

- agixt/prompts/Summarize Web Content.txt
Add Summarize Web Content prompt
> Add Summarize Web Content prompt

- agixt/Interactions.py
> Add disable memory param

- agixt/Interactions.py
- agixt/Memories.py
- agixt/prompts/Summarize Web Content.txt
- tests/tests.ipynb
WebSearch Memory Optimization
- During web searches, the websearch agent will now prompt the AI with chunks of 2000 characters from the website that it is browsing and ask it to summarize what is relevant to the task.  Only what it summarizes will be committed to memory, this will make the AI disregard adding anything that isn't relevant to the task to memory.
> WebSearch Memory Optimization

- agixt/Interactions.py
Improve code structure for WebSearch agent
> Improve code structure for WebSearch agent

- agixt/prompts/Title a Chain.txt
previous prompt was a bit too complicated and sometimes resulted in full summaries getting outputted instead of 5 words titles
> simplier and more stable prompt for 5 for filename title generation

- agixt/provider/llamacppapi.py
> Async instruct to fix #733

- agixt/provider/oobabooga.py
Improve ooba provider thanks to @daouid
> Improve ooba provider

- agixt/extensions/agixt_chain.py
- agixt/extensions/file_system.py
- agixt/provider/custom.py
Add sleep to custom provider.  Bugfixes
> Add sleep to custom provider.  Bugfixes

- agixt/extensions/agixt_chain.py
- agixt/prompts/Convert OpenAPI Endpoint.txt
- agixt/provider/bard.py
- agixt/provider/custom.py
- requirements.txt
Fix Bard formatting for task chain
> Fix Bard formatting for task chain

- agixt/provider/custom.py
Add custom sleep after failure and sleep between requests to Custom provider.
> Add custom sleep after failure and sleep between requests

- agixt/example.ipynb
- agixt/provider/custom.py
- agixt/provider/oobabooga.py
Add prompt prefix and suffix for ooba
> Add prompt prefix and suffix for ooba

- agixt/chains/Generate and Run Smart Task Chain.json
Update Generate and Run Smart Task Chain
- Fix Typo.
> Update Generate and Run Smart Task Chain

- agixt/chains/Generate and Run Task Chain.json
> Update Generate and Run Task Chain

- AGiXT.sh
> add tokenizer var to script

- streamlit/components/history.py
> Change line break in history

- agixt/Interactions.py
Fix improper logging from issue #759
> Fix improper logging from issue #759

- agixt/chains/Generate Smart Task Chain without Research.json
- agixt/chains/Generate Smart Task Chain.json
- agixt/chains/Generate Task Chain without Research.json
- agixt/chains/Generate Task Chain.json
- agixt/chains/Generate and Run Smart Task Chain.json
- agixt/chains/Generate and Run Task Chain.json
- agixt/chains/Smart Instruct - No Research.json
- agixt/extensions/agixt_chain.py
Merge Smart Task Chain Functions
- Address  #769 to make non-researching chains also not research even if smart.
> Merge Smart Task Chain Functions

- streamlit/components/selectors.py
> Cache prompts in chain page

- agixt/prompts/Get Task List.txt
No commands on task list creation
> No commands on task list creation

- agixt/Interactions.py
- Will give the ability to start/resume a chain from any step on back end, haven't implemented any change for front end yet.
> Add from_step param to run_chain

- agixt/Interactions.py
> Fixed float issue

- agixt/Interactions.py
> Await memory store

- agixt/Interactions.py
- agixt/prompts/Instruction.txt
- agixt/prompts/SmartInstruct-Execution.txt
- agixt/prompts/Task Execution.txt
- agixt/prompts/instruct.txt
Add working directory to prompts
> Add working directory to prompts

- agixt/chains/Generate Smart Task Chain without Research.json
- agixt/chains/Generate Smart Task Chain.json
- agixt/chains/Generate Task Chain without Research.json
- agixt/chains/Generate Task Chain.json
- agixt/chains/Generate and Run Smart Task Chain.json
- agixt/chains/Generate and Run Task Chain.json
- agixt/extensions/agixt_chain.py
- agixt/prompts/Break into steps.txt
- agixt/prompts/Task Execution.txt
- Smart Prompt chain has been improved and tested well to take a basic user prompt and turning it into a more detailed prompt that will help the AI to be more descriptive and give it the best context for what you need done in your task, such as telling it what kind of expert to act as based on your task given.
- Each task in task generation are now abstracted by smart prompts for better results.
> Smarter Smart Chains for Task Generation

- agixt/provider/azure.py
- agixt/provider/bing.py
- agixt/provider/claude.py
- agixt/provider/custom.py
- agixt/provider/gpt4all.py
- agixt/provider/gpt4free.py
- agixt/provider/gpugpt4all.py
- agixt/provider/huggingchat.py
- agixt/provider/huggingface.py
- agixt/provider/kobold.py
- agixt/provider/llamacpp.py
- agixt/provider/llamacppapi.py
- agixt/provider/palm.py
- agixt/provider/runpod.py
- agixt/provider/transformer.py
> Force defaults for providers

- agixt/Agent.py
Improve autonomous execution
- Forced to boolean.
> Improve autonomous execution

- agixt/provider/gpt4free.py
- requirements.txt
update gpt4free to V2
use the v2 as explain in the gpt4free
> update gpt4free to V2

- agixt/Interactions.py
- agixt/Memories.py
- agixt/app.py
- agixt/chains/Smart Chat - No Research.json
- agixt/chains/Smart Chat.json
- agixt/chains/Smart Instruct - No Research.json
- agixt/prompts/SmartChat-Researcher.txt
- agixt/prompts/SmartChat-Resolver.txt
- agixt/prompts/SmartInstruct-Researcher.txt
- agixt/prompts/SmartInstruct-Resolver.txt
- agixt/prompts/WebSearch.txt
Smart chain shot fix
- `shots` was being used twice causing issues in how many shots were happening on each step of smart chat/instruct.  This has been fixed.
> Smart chain shot fix

- .github/workflows/publish-docker.yml
> Fix test notebook requirements

- agixt/extensions/agixt_agent.py
- agixt/prompts/Ask for Help.txt
- agixt/prompts/Create New Command.txt
- agixt/prompts/Evaluate Code.txt
AGiXT Extension Rework
- The code evaluation functions were not working properly, will all be reworked into chains then added back as chains to run.
- Added "Ask for Help or Further Clarification to Complete Task" command to make the AI reflect on the problem it is working on.
> AGiXT Extension Rework

- agixt/extensions/agixt_agent.py
- agixt/extensions/agixt_chain.py
- agixt/prompts/Ask for Help.txt
- agixt/prompts/Get Clarification.txt
> Conversational reflection

- streamlit/pages/0-Agent_Settings.py
> Fix helper agent settings

- agixt/Agent.py
- agixt/Chain.py
- agixt/Embedding.py
- agixt/Interactions.py
- agixt/Memories.py
- agixt/app.py
- agixt/provider/gpt4free.py
- streamlit/pages/0-Agent_Settings.py
- tests/tests.ipynb
Code cleanup/prep for DB migration
> Code cleanup/prep for DB migration

- agixt/Chain.py
- agixt/Interactions.py
- requirements.txt
> Update Poe, More code cleanup

- agixt/Interactions.py
- streamlit/pages/0-Agent_Settings.py
Add autonomos execution checkbox to agent settings
> Add autonomos execution checkbox to agent settings

- agixt/Interactions.py
- agixt/app.py
Add tokens to OpenAI style returns
> Add tokens to OpenAI style returns

- streamlit/components/selectors.py
- streamlit/pages/0-Agent_Settings.py
> Fix helper agent selector

- .env.example
- AGiXT.sh
> Add auto updater feature

- agixt/app.py
Add embedding endpoint
- `api/v1/embedding` takes two arguments, `input` and `model`.  The `model` is going to be your `agent_name`, the input is whatever you want that agent to get the embeddings for.
> Add embedding endpoint

- agixt/Interactions.py
When interactions run , disable_memory value not work.
write a sample test.py  set prompt_args.disable_memory = True，
```
from agixtsdk import AGiXTSDK
import os
ApiClient = AGiXTSDK(
base_uri="http://localhost:7437", api_key=""
)
results = ApiClient.prompt_agent(
agent_name="my_test_agent",
prompt_name="WebSearch",
prompt_args={
"user_input": "马云是谁",
"disable_memory": True,
},
)
print(results)
```
set some logging in Interactions.py
```
.....
if self.response != "" and self.response != None:
if disable_memory != True:
try:
logging.info(f"disable_memory != True store_result: {self.response}")
await self.memories.store_result(
input=user_input, result=self.response
)
except:
pass
.....
```
this code is work!
> fix Interactions.run() disable_memory value

- agixt/Interactions.py
Browse sublinks based on selected depth
> Browse sublinks based on selected depth

- docker-compose-local-nvidia.yml
- docker-compose-postgres-local-nvidia.yml
- docker-compose-postgres.yml
- docker-compose.dev.yaml
- docker-compose.yml
Make .env file persist in container
- Potentially fixes #867
> Make .env file persist in container

- agixt/Interactions.py
- agixt/app.py
- agixt/db/History.py
- agixt/fb/History.py
Add UUID as default conversation ID
> Add UUID as default conversation ID

- Dockerfile
- agixt/Memories.py
- requirements.txt
Lower ChromaDB version to 0.3.29
> Lower ChromaDB version to 0.3.29

- AGiXT.sh
The dependencies need to be upgraded for the streamlit module and may be the hub module.
I got an error with the agixtsdk which was in 0.0.17 and streamlit try to call get_chain_args but wasn't found so --upgrad is needed in the installation file AGiXT.sh
I add --upgrade to others module to don't miss any lib update
> auto update dependencies for modules

- AGiXT.sh
- agixt/Embedding.py
fix of a small omission 
Sorry for the two useless commit xD
> fix Embedding.py

- agixt/Memories.py
- agixt/app.py
> Add branch to github learning

- agixt/providers/gpt4free.py
- requirements.txt
g4f provider updated
Adding the Js2Py dep and then can be removed when [this pr](https://github.com/xtekky/gpt4free/pull/796) will be merged
In the second commit I change psycopg2 to psycopg2-binary because the first one is building from source and it need some requirements 
I catch another problem:
the requirements are not updated with th AGiXT.sh may be because of this condition `  if [ ! -d "agixt/providers" ]; then` line 253 and Idk how to fix it
> Some fixes

- agixt/app.py
> Add learn text endpoint

- requirements.txt
> Remove old requirements

- agixt/readers/file.py
Clean up workspace restriction references
> Clean up workspace restriction references

- docker-compose-local-nvidia.yml
- docker-compose-postgres-local-nvidia.yml
- docker-compose-postgres.yml
- docker-compose.dev.yaml
- docker-compose.yml
Add AGiXT API key to docker compose files
> Add AGiXT API key to docker compose files

- agixt/app.py
> Fix add_prompt

- agixt/ApiClient.py
- agixt/Chains.py
- agixt/Interactions.py
- agixt/Memories.py
- agixt/Websearch.py
- agixt/__init__.py
- agixt/app.py
- agixt/db/Chain.py
- agixt/fb/Chain.py
- agixt/providers/agixt.py
- agixt/providers/openai.py
> Clean up ApiClient refs

- AGiXT.sh
- docker-compose-local-nvidia-sd.yml
- docker-compose-postgres-local-nvidia-sd.yml
- models/Codeformer/placeholder
- models/Stable-diffusion/placeholder
- models/hypernetworks/placeholder
Add option to run Stable Diffusion locally to installer
> Add option to run Stable Diffusion locally to installer

- agixt/providers/perplexity.py
- requirements.txt
Add Perplexity provider ask in #711 
It can be hard to setup this provider.
Especially to get the cookies:
You need to follow almost what is written [here](https://github.com/helallao/perplexity-ai/tree/main#how-to-get-the-cookies).
But instead of taking their curlconverter link, you need to use [this](https://curlconverter.com/json/) (replace python by json and save the json the same way the hugging cookie is saved.
Tested by the main function only
> Add Perplexity provider

- AGiXT.sh
- Dockerfile
- docker-compose-dev-nvidia.yml
- requirements.txt
Add dev nvidia option to setup script
> Add dev nvidia option to setup script

- agixt/app.py
- tests/tests.ipynb
> Fix delete prompt

- agixt/providers/nbox.py
Add provider for this [api](https://chat.nbox.ai/)
> Add nbox provider

- agixt/providers/nbox.py
> nbox little fix

- docker-compose-dev-nvidia.yml
- docker-compose-local-nvidia-sd.yml
- docker-compose-local-nvidia.yml
- docker-compose-postgres-local-nvidia-sd.yml
- docker-compose-postgres-local-nvidia.yml
Restart Text Generation Web UI container if it dies
> Restart Text Generation Web UI container if it dies

- agixt/app.py
Add conversation/{name} endpoint
> Add conversation/{name} endpoint

- agixt/Interactions.py
Update command execution output
> Update command execution output

- agixt/Interactions.py
Improve instruct and add nested commands
- Resolves #294
> Improve instruct and add nested commands

- agixt/providers/gpt4free.py
- agixt/providers/perplexity.py
- requirements.txt
There is a problem with g4f
The g4f code is calling` yield asyncio.run` that cause an error `Cannot run the event loop while another loop is running`
And the fix is for perplexity (improvement)
> g4f update + perplexity.py fixes

- agixt/providers/gpt4free.py
- agixt/providers/perplexity.py
- requirements.txt
> Revert "g4f update + perplexity.py fixes"

- docker-compose-dev-nvidia.yml
- docker-compose-dev.yml
- docker-compose-local-nvidia-sd.yml
- docker-compose-local-nvidia.yml
- docker-compose-postgres-local-nvidia-sd.yml
- docker-compose-postgres-local-nvidia.yml
- docker-compose-postgres.yml
- docker-compose.yml
Add NextJS front end to docker-compose
- NextJS front end will be accessible at http://localhost:24498
> Add NextJS front end to docker-compose

- agixt/readers/file.py
> Add audio to file reader

- agixt/app.py
- agixt/db/History.py
- agixt/fb/History.py
- requirements.txt
Add content to new conversation function
> Add content to new conversation function

- agixt/providers/custom.py
- agixt/providers/openai.py
Add comma separated uri support
- Custom provider and OpenAI provider will now accept commas in the uri to separate and rotate between as many providers as you want.  It will randomly select a URI from the list to use.
> Add comma separated uri support

- agixt/Providers.py
> Improve provider options

- agixt/DBConnection.py
Expand database support
- Adding support for `SQLite`, `MS SQL`, `MySQL`, and `Oracle` to use for databases as alternatives to `PostgreSQL`.
> Expand database support

- docs/1-Getting started/1-Environment Variables.md
- docs/2-Concepts/1-AGiXT Hubs.md
- docs/2-Concepts/4-Extension Commands.md
- docs/README.md
Remove hub references from docs
> Remove hub references from docs

- docker-compose-dev-nvidia.yml
- docker-compose-dev.yml
- docker-compose-local-nvidia-sd.yml
- docker-compose-local-nvidia.yml
- docker-compose-postgres-local-nvidia-sd.yml
- docker-compose-postgres-local-nvidia.yml
- docker-compose-postgres.yml
- docker-compose.yml
> Add compose version for #994

- agixt/providers/bard.py
- requirements.txt
Switch bard module to `bardapi`
- GoogleBard module has been archived and no longer works.
- `bardapi` repository: https://github.com/dsdanielpark/Bard-API
> Switch bard module to bardapi

- agixt/DBConnection.py
- agixt/launch-backend.sh
> Clean up launcher script

- agixt/ApiClient.py
- agixt/DBConnection.py
- agixt/Interactions.py
- agixt/db/Agent.py
- agixt/db/Chain.py
- agixt/db/History.py
- agixt/db/Prompts.py
- agixt/db/imports.py
- agixt/endpoints/Agent.py
- agixt/endpoints/Chain.py
- agixt/endpoints/Completions.py
- agixt/endpoints/Conversation.py
- agixt/endpoints/Extension.py
- agixt/endpoints/Memory.py
- agixt/endpoints/Prompt.py
- agixt/endpoints/Provider.py
- requirements.txt
Add user for future functionality
> Add user for future functionality

- agixt/Chains.py
- agixt/db/Agent.py
- agixt/db/Chain.py
- agixt/db/History.py
- agixt/db/Prompts.py
- agixt/db/imports.py
- agixt/endpoints/Agent.py
- agixt/endpoints/Chain.py
- agixt/endpoints/Completions.py
- agixt/endpoints/Conversation.py
- agixt/endpoints/Extension.py
- agixt/endpoints/Memory.py
- agixt/endpoints/Prompt.py
- agixt/fb/Agent.py
- agixt/fb/Chain.py
- agixt/fb/History.py
- agixt/fb/Prompts.py
> Add user refs

- agixt/Chains.py
- agixt/Interactions.py
> Add more user refs

- agixt/DBConnection.py
- agixt/db/Agent.py
- agixt/db/Chain.py
- agixt/db/History.py
- agixt/db/Prompts.py
- agixt/db/imports.py
> Add user connections

- Dockerfile
- agixt/extensions/agixt_actions.py
- agixt/extensions/file_system.py
- static-requirements.txt
Containerize python code execution
> Containerize python code execution

- agixt/Interactions.py
Add RLHF context injection
- If there is anything with a 0.7 or higher relevance score in the positive or negative feedback collections for the agent, the top 3 results from RLHF collections will be injected.
> Add RLHF context injection

- agixt/providers/llamacpp.py
Improve llamacpp integration
- Made all llamacpp fields configurable in agent settings for any agent with that provider set.
> Improve llamacpp integration

- requirements.txt
Update llama-cpp-python to v0.2.8
> Update llama-cpp-python to v0.2.8

- agixt/Interactions.py
> Add provider error logging

- agixt/providers/llamacppapi.py
- Added all parameters from the llamacpp server documentation to be configurable
- Added comment with Instructions for setting up llama.cpp server: https://github.com/ggerganov/llama.cpp/tree/master/examples/server#llamacppexampleserver
> Make all params available for llamacpp api

- requirements.txt
> Update g4f and llamacpp

- agixt/Embedding.py
- agixt/providers/local.py
> Add Local-LLM embedder

- requirements.txt
> Update gpt4free to 0.1.4.9

- requirements.txt
> Update gpt4free to 0.1.5.0

- requirements.txt
> Update gpt4free to 0.1.5.6

- Dockerfile
Attempt to use python:3.10-buster
> Attempt to use python:3.10-buster

- requirements.txt
> Update hugchat to 0.3.3

- requirements.txt
> Update g4f to 0.1.6.2

- requirements.txt
Update g4f and hugchat
```
g4f==0.1.6.6
hugchat==0.3.6
```
> Update g4f and hugchat

- requirements.txt
> Update Local-LLM to 0.0.15

- docs/README.md
This Pull Request fixes a typographical error in the README.md file.
- Corrected "Repositorities" to "Repositories" in the README.md file.
This fix is not related to any existing issue. It's a minor typo that I noticed while reviewing the README.
Thank you for considering this contribution.
> doc(README): remove typo

- requirements.txt
> Update Local-LLM to v0.0.18

- agixt/providers/kobold.py
- docs/3-Providers/Kobold.md
- Fixes #1023
- Added new parameters supported by KoboldAI and KoboldCpp APIs
- Updated documentation
- I was having some problems having my local llm giving me gibberish.
- The Kobold provider was missing some parameters so I decided to add them and add support for the KoboldAI api while I was at it.
Tested in a local environment.
> Refactor Kobold provider

- Dockerfile
- requirements.txt
Latest g4f version is giving errors. Locking to g4f==0.1.9.8
> Downgrade g4f

- AGiXT.ps1
- agixt/Embedding.py
- agixt/providers/local.py
- docker-compose-dev-cuda.yml
- docker-compose-dev.yml
Use containerized Local-LLM for better performance
- This is a dev option for now. Replacing the Local-LLM provider due to performance with using it from a container, which has shown great performance increases.
> Use containerized Local-LLM for better performance

- agixt/prompts/Default/Bully.txt
> Added Bully Prompt.

- agixt/providers/gemini.py
> Add Google Gemini 

- .github/workflows/operation-test-with-jupyter.yml
- .github/workflows/publish-docker-dev.yml
Add dev branch tests
- This will run tests on any branch so that we can confirm that tests passed in PRs
> Add dev branch tests

- agixt/providers/nvidia.py
- docs/3-Providers/Nvidia.md
> Add Nvidia Provider and Documentation

- agixt/providers/nvidia.py
> Hotfix Only output content on Nvidia provider

- docs/1-Getting started/2-Install Options.md
- docs/1-Getting started/Screenshots.md
Update docs for #1125
- Removed screenshot from old installer.
- Updated Install Options page to reflect the install options available now.
> Update docs for #1125

- agixt/providers/nvidia.py
- docs/3-Providers/Nvidia.md
> Fix provider and update docs

- agixt/Interactions.py
Command execution improvements
- Retrieving a more accurate list of commands available to the agent in the execution agent
- Will now only inject the wrapper of the command execution prompt if the agent has available commands enabled.
> Command execution improvements

- docs/2-Concepts/0-Core Concepts.md
More details are added and clarified. Some features are also updated based on the current code.
More details are added and clarified. Some features are also updated based on the current code.
> Update 0-Core Concepts.md

- docs/2-Concepts/00- Processes and Frameworks.md
describing the architecture of AGiXT
This file describes the whole architecture of AGiXT and its framework for Web UI.
> Create 00- Processes and Frameworks.md

- agixt/Models.py
- agixt/endpoints/Completions.py
- agixt/endpoints/Memory.py
- agixt/readers/youtube.py
- requirements.txt
- Added YouTube captions reader and associated endpoint `/api/agent/{agent_name}/learn/youtube`.
- Added YouTube and GitHub readers to chat completions pipeline.
> Add YouTube captions reader

- agixt/endpoints/Completions.py
- agixt/providers/claude.py
- agixt/providers/ezlocalai.py
- agixt/providers/google.py
- agixt/providers/huggingface.py
- agixt/providers/openai.py
- Add Gemini vision to Google provider.
- Convert incoming audio to wav on chat completions endpoint
> Add Gemini Vision, convert incoming audio

- agixt/Interactions.py
Add vision and image creation to main pipeline
- If you pass images to the chat completions endpoint, it will send them to the vision model first, get the vision models response, and pass that response in context to the LLM with context injected and wrapped in the selected prompt template. 
- I have been getting significantly better responses by not relying on vision models to be logical and using their response in context to a more logical LLM, or as essentially a second shot with context.
> Add vision and image creation to main pipeline

- docs/2-Concepts/04-Chat Completions.md
Added YouTube and GitHub details.
> Update 04-Chat Completions.md

- agixt/ApiClient.py
- agixt/app.py
- agixt/endpoints/Completions.py
- agixt/providers/ezlocalai.py
- agixt/providers/huggingface.py
- Improvement to TTS pipeline
- Add outputs static directory to output audio as URLs from workspace. Will expand on this further later to doing the same with images and anything else an agent generates.
> Improvement to TTS pipeline, Add outputs static directory

- agixt/Chains.py
- agixt/db/Chain.py
- agixt/fb/Chain.py
Fix chain responses
- Should fix #1182
> Fix chain responses

- tests/tests.ipynb
> Fix typo in test

- agixt/Interactions.py
- agixt/Websearch.py
- agixt/XT.py
Use `ACTIVITY` instead of `ACTIVITY_START` and `ACTIVITY_END`
> Use `ACTIVITY` instead of `ACTIVITY_START` and `ACTIVITY_END`

- agixt/Websearch.py
- agixt/extensions/google.py
Move google search to Websearch.py
- All websearch functions have been removed from extensions and moved to Websearch.py so that they will all properly browse using the same browsing functions that properly chunk memories into the correct collections.
> Move google search to Websearch.py

- agixt/Interactions.py
- agixt/XT.py
Use URL for image uploads instead of passing file path.
> Use URL for image uploads

- agixt/XT.py
- docs/2-Concepts/04-Chat Completions.md
Code reduction on chat completions function
- Reduces all specified file types and handles the different kinds of files in the new `download_file_to_workspace` function.
> Code reduction on chat completions function

- agixt/Interactions.py
- agixt/Websearch.py
- agixt/XT.py
Add GitHub Repo Download to Memory to Chat Completions
> Add GitHub Repo Download to Memory to Chat Completions

- agixt/Conversations.py
- agixt/DB.py
- requirements.txt
Add user preferences and timezones
- It will currently only automatically set the user timezone as the one set in the `TZ` environment variable. Will expand on this more later but merging to get initial functionality in place.
> Add user preferences and timezones

- agixt/MagicalAuth.py
- agixt/registration_requirements.json
- docker-compose-dev.yml
- docker-compose.yml
> Add requirements

- Dockerfile
- agixt/Globals.py
- agixt/Interactions.py
- agixt/Memories.py
- agixt/XT.py
- agixt/agents/gpt4free/config.json
- agixt/providers/gpt4free.py
- requirements.txt
- Updated `nodejs` in the container to v20. It is used by `playwright`.
- Reverted `g4f` to `v0.2.6.2` due to breaking changes they made after that to using browsers. I haven't figured out how to properly integrate with their current system due to missing requirements in the container. I attempted adding several `pip` requirements as well as the `chromium` and `chromium-sandbox` `apt` packages in the container to try to fix it, but was unsuccessful.
> Rework g4f, update Nodejs

- agixt/Conversations.py
- agixt/Interactions.py
- agixt/Models.py
- agixt/Tuning.py
- agixt/XT.py
- agixt/endpoints/Agent.py
- agixt/endpoints/Chain.py
- agixt/endpoints/Completions.py
- agixt/endpoints/Conversation.py
- agixt/endpoints/Memory.py
Initialize AGiXT class with conversation name
- Most functions in the class need it for logging activities. 
- Requesting things like the conversation ID less frequently should improve performance.
> Initialize AGiXT class with conversation name

- agixt/prompts/Default/Convert OpenAPI Endpoint.txt
> chore: update Convert OpenAPI Endpoint.txt

- agixt/extensions/github.py
> add get repos for user

- agixt/Agent.py
Add user settings to agent settings
- If any keys are defined in `registration_requirements.json`, those user settings will be injected as final overrides to any agents they interact with.
> Add user settings to agent settings

- agixt/extensions/oura.py
- More information on the API: https://cloud.ouraring.com/v2/docs
> Add Oura Ring extension

- agixt/Globals.py
- agixt/MagicalAuth.py
- agixt/endpoints/Agent.py
Create default agent if it doesn't exist on `get_agents`
> Create default agent if it doesn't exist on `get_agents`

- agixt/Agent.py
- agixt/Interactions.py
Improve command execution guidelines
> Improve command execution guidelines

- docs/README.md
> Add Dart SDK badge to readme

- agixt/Chain.py
fixes the problem when importing chain AttributeError: 'NoneType' object has no attribute 'id'
> fix import chain AttributeError: 'NoneType' object has no attribute 'id'

- agixt/XT.py
- agixt/extensions/github.py
- agixt/prompts/Default/Think About It.txt
Auto continue was added in https://github.com/Josh-XT/AGiXT/pull/1258 , but I only had it set to continue one time. This update allows it to infinitely continue until the agent decides it is done responding granting an equal amount of output tokens as their input tokens.
> Always auto continue if enabled

- agixt/Interactions.py
Changing command execution format to:
```xml
<execute>
<name>FRIENDLY COMMAND NAME</name>
<arg1>content</arg1>
<arg2>content</arg2>
</execute>
```
> Change command execution format

- agixt/XT.py
- agixt/extensions/minecraft.py
Took inspiration from some cool stuff on X and fed it to my Claude agent to see what it could make. I haven't tested it and I don't even play Minecraft, could be something fun for someone that does to play with.
> Add Minecraft extension

- agixt/Interactions.py
- agixt/XT.py
- agixt/extensions/github.py
- agixt/prompts/Default/Think About It.txt
- agixt/providers/gpt4free.py
- tests/endpoint-tests.ipynb
This pull request includes significant changes to the `agixt` codebase, focusing on removing unnecessary features, improving prompt formatting, and updating test configurations. The most important changes are outlined below:
* Removed `github_memories` initialization and usage from `agixt/Interactions.py`. This includes the removal of its initialization in the `__init__` method and its usage in the `format_prompt` method. [[1]](diffhunk://#diff-66ea3aae1abe5007b7f1de0b4d4c558a874642fc8338652546e9a26d3c74c5e9L71-L77) [[2]](diffhunk://#diff-66ea3aae1abe5007b7f1de0b4d4c558a874642fc8338652546e9a26d3c74c5e9L86) [[3]](diffhunk://#diff-66ea3aae1abe5007b7f1de0b4d4c558a874642fc8338652546e9a26d3c74c5e9L158-L162)
* Added new guidelines for the assistant's behavior and response formatting in …
> Add long reasoning command execution functionality

- agixt/Conversations.py
- agixt/MagicalAuth.py
- agixt/Task.py
- agixt/TaskMonitor.py
- agixt/extensions/agixt_actions.py
- agixt/launch-backend.sh
This pull request introduces several new features and improvements, mainly focusing on task management and user impersonation. The most important changes include the addition of a task management system, user impersonation functionality, and updates to the backend launch script to include a task monitor.
* [`agixt/Task.py`](diffhunk://#diff-817856d13e65608f5a1829552e47c268022c968f1199889337e63ed6106e50c3R1-R230): Introduced a new `Task` class with methods for creating, updating, and managing tasks, including handling AI follow-up tasks.
* [`agixt/TaskMonitor.py`](diffhunk://#diff-6cc98a0b8865dee128f95606a8964dc0dcef30093b39d7527c5f3a368c5325fbR1-R73): Added a `TaskMonitor` class to continuously check and execute pending tasks for all users, ensuring tasks are handled even when the user is …
> Add task scheduling

- agixt/extensions/github.py
Add smart replacement functions as GitHub commands
This PR introduces significant improvements to AGiXT's GitHub extension, specifically enhancing the file modification capabilities. The changes focus on making the system more consistent with AGiXT's existing command structure while improving how language models interact with and understand the file modification commands.
- Refactored file modification system to use AGiXT's XML-style command format
- Introduced separate commands for common operations:
- `Modify File Content` (batch modifications)
- `Replace in File` (single replacement)
- `Insert in File` (single insertion)
- `Delete from File` (single deletion)
- Maintained smart indentation handling and fuzzy matching capabilities
- Added comprehensive docstrings with detailed …
> Add smart replacement functions as GitHub commands

- agixt/Interactions.py
This pull request includes changes to the `agixt/Interactions.py` file, focusing on enhancing the flexibility of command handling in the `format_prompt` and `run` methods. The most important changes include adding a check for the `disable_commands` keyword argument to conditionally disable command-related functionality.
Enhancements to command handling:
* [`agixt/Interactions.py`](diffhunk://#diff-66ea3aae1abe5007b7f1de0b4d4c558a874642fc8338652546e9a26d3c74c5e9R418): Added a check for the `disable_commands` keyword argument in the `format_prompt` method to conditionally skip the inclusion of commands.
* [`agixt/Interactions.py`](diffhunk://#diff-66ea3aae1abe5007b7f1de0b4d4c558a874642fc8338652546e9a26d3c74c5e9L433-R434): Adjusted the formatting of the `agent_commands` string in the …
> Add disable commands override for interactions

- agixt/DB.py
- agixt/Extensions.py
- agixt/SeedImports.py
- agixt/Websearch.py
- agixt/extensions/agixt_actions.py
- agixt/extensions/web_browsing.py
This pull request includes several changes to the `agixt` project, focusing on adding new functionality and improving existing features. The most important changes include adding environment variables, extending the `execute_command` method, and introducing a new web search function.
* [`agixt/Extensions.py`](diffhunk://#diff-d9cd0a71232406e3215825617ef8c1b3be5768a5a886db839c7ab04e0844f2b2R345): Added the `AGIXT_URI` environment variable to the `execute_command` method to dynamically set the `output_url`. [[1]](diffhunk://#diff-d9cd0a71232406e3215825617ef8c1b3be5768a5a886db839c7ab04e0844f2b2R345) [[2]](diffhunk://#diff-d9cd0a71232406e3215825617ef8c1b3be5768a5a886db839c7ab04e0844f2b2R359)
* [`agixt/Websearch.py`](diffhunk://#diff-cb0dd9a16a43d04d91cb83e4f3442829c8d8fad7f80f01a463c98c91f9fdb …
> Update web browsing extension

- agixt/providers/deepseek.py
- agixt/providers/xai.py
This pull request introduces two new provider classes, `DeepseekProvider` and `XaiProvider`, to the `agixt/providers` directory. These classes are designed to interact with the Deepseek and xAI APIs, respectively, for various AI services.
New provider classes:
* [`agixt/providers/deepseek.py`](diffhunk://#diff-4cda23eea6e5364b67d556e26f62373b65a9c5cbd6be8f5b487c03cd133b2d99R1-R108): Added the `DeepseekProvider` class to interact with the Deepseek API, including methods for setting up API parameters and performing inference with support for text and image inputs.
* [`agixt/providers/xai.py`](diffhunk://#diff-a8f3ca0421d7e8e703f9b25f70e64ce023842f4367a9c56eaa812511e56acad0R1-R106): Added the `XaiProvider` class to interact with the xAI API, including methods for setting up API parameters …
> add deepseek and xai

- agixt/Agent.py
- agixt/endpoints/Completions.py
- agixt/providers/anthropic.py
- agixt/providers/rotation.py
This pull request includes significant updates to the `AGiXT` project, focusing on improving the handling of provider settings, enhancing chunk analysis functionality, and refining provider selection logic. The most important changes include modifications to the `Agent` class initialization, addition of chunk scoring and content chunking methods, and updates to the `RotationProvider` class to support parallel chunk analysis and better provider management.
* [`agixt/Agent.py`](diffhunk://#diff-556d8be092ab95b9c185df744d2b3c8f7ad8652b5819506599877fd2a9cead8dR225-R234): The `__init__` method of the `Agent` class now deletes specific keys from `PROVIDER_SETTINGS` and includes additional parameters (`agent_name`, `user`, `api_key`) when initializing the `Providers` instance. …
> Smarter rotation provider

- agixt/Agent.py
- agixt/Interactions.py
- agixt/Workspaces.py
- docker-compose-dev.yml
> Improved command injection

- .github/workflows/build-and-test.yml
- .github/workflows/tests.yml
- agixt/Chain.py
- agixt/DB.py
- agixt/MagicalAuth.py
- agixt/Models.py
- agixt/Task.py
- agixt/TaskMonitor.py
- agixt/app.py
- agixt/endpoints/Agent.py
- agixt/endpoints/Chain.py
- agixt/endpoints/Completions.py
- agixt/endpoints/Conversation.py
- agixt/endpoints/Extension.py
- agixt/endpoints/Memory.py
- agixt/endpoints/Prompt.py
- agixt/endpoints/Provider.py
This issue is in reference to #1354 
The changes aim to improve functionality, simplify configurations, and enhance the API documentation.
This pull request includes several changes to the workflow configuration files and the AGiXT module's models and endpoints. The most important changes include the addition of new response models in `agixt/Models.py`, and enhancements to the `agixt/endpoints/Agent.py` and `agixt/endpoints/Chain.py` files to provide detailed API responses and descriptions.
* [`agixt/Models.py`](diffhunk://#diff-961111329070aad337c99ef6d709fb4a727a9bb05365b0d18c3b105741e0f734R435-R588): Added multiple new response models such as `ProvidersResponse`, `ProviderSettings`, `AgentResponse`, `AgentListResponse`, and many others to standardize API responses.
* …
> Add docs to endpoints

- docs/README.md
> add rust badge

- docs/README.md
> Add Zig Badge

- docs/README.md
> add Pumpfun badge

- docs/README.md
> correct logo and add videos

- agixt/Agent.py
- agixt/Models.py
- agixt/app.py
- agixt/endpoints/Wallet.py
- agixt/extensions/solana_wallet.py
Allows Agent to have wallet and everything! endpoint added. Resolves #1422
> Solana Wallet 

- agixt/MagicalAuth.py
- agixt/endpoints/Auth.py
- agixt/sso/amazon.py
- agixt/sso/github.py
- agixt/sso/google.py
- agixt/sso/microsoft.py
- agixt/sso/tesla.py
- agixt/sso/walmart.py
- agixt/sso/x.py
> Add oauth provider endpoint

- agixt/MagicalAuth.py
- agixt/endpoints/Auth.py
- agixt/sso/amazon.py
- agixt/sso/discord.py
- agixt/sso/github.py
- agixt/sso/google.py
- agixt/sso/microsoft.py
- agixt/sso/tesla.py
- agixt/sso/walmart.py
- agixt/sso/x.py
This PR resolves #1421 
- Add /v1/oauth2/pkce-simple endpoint for code_verifier and code_challenge generation
- Adapt all sso providers for potential PCKE support
- Fix outdated urls and request params in the X SSO provider 
> Add PKCE support and Fix X OAuth login

- agixt/Agent.py
- agixt/Chain.py
- agixt/Extensions.py
- agixt/Models.py
- agixt/SeedImports.py
- agixt/endpoints/Chain.py
- agixt/endpoints/Extension.py
- agixt/endpoints/GQL.py
> Add description to chains

- agixt/extensions/ai.py
- agixt/extensions/github.py
- agixt/extensions/web_browsing.py
- agixt/providers/google.py
Improve web browsing and file modification logic
This pull request introduces a new AI extension for AGiXT and includes improvements to error handling and logging in the GitHub extension. The most significant changes involve adding a new `ai` class with multiple AI capabilities, enhancing error handling for XML parsing in file modification operations, and improving logging for parsing failures.
* Added a new `ai` class in `agixt/extensions/ai.py` that provides functionalities such as chat completions, image generation, and text-to-speech. This includes methods like `chat_completions`, `generate_image`, and `text_to_speech`, along with initialization logic to configure API clients and directories.
* Updated `modify_file_content` in `agixt/extensions/github.py` to handle cases where …
> Improve web browsing and file modification logic

- agixt/MagicalAuth.py
This pull request introduces timezone-aware expiration date calculations for magic links in the `send_magic_link` function of `agixt/MagicalAuth.py`. The changes ensure that expiration times are calculated based on the server's timezone, defaulting to UTC if the timezone is not set or invalid.
* **Timezone handling added**: Imported `ZoneInfo` and `ZoneInfoNotFoundError` to enable timezone-aware datetime operations.
* **Expiration logic updated**: Replaced the previous fixed expiration logic with a detailed calculation that:
1. Fetches the timezone from the `TZ` environment variable (defaulting to UTC if unset or invalid).
2. Uses the server's timezone to calculate the expiration datetime for the first day of the next month at midnight.
> Improve JWT expiration time

- agixt/Chain.py
- agixt/Extensions.py
- agixt/MagicalAuth.py
- agixt/Memories.py
- agixt/Providers.py
- agixt/TaskMonitor.py
- agixt/Websearch.py
- agixt/Workspaces.py
- agixt/XT.py
- agixt/endpoints/Agent.py
- agixt/endpoints/Auth.py
- agixt/endpoints/Memory.py
- agixt/endpoints/TeslaIntegration.py
> Clean up logging

- agixt/endpoints/Conversation.py
- docs/websocket-conversation-streaming.md
- docs/websocket-implementation-summary.md
- examples/test_websocket_conversation.py
- examples/websocket_test.html
This pull request introduces a WebSocket endpoint for real-time conversation streaming in the AGiXT system, along with comprehensive documentation and implementation details. The changes include adding the WebSocket functionality, providing detailed API documentation, and summarizing the technical implementation. This enables clients to subscribe to conversation updates and receive notifications for new, updated, or deleted messages in real time.
* **File `agixt/endpoints/Conversation.py`**: Added a WebSocket endpoint `/v1/conversation/{conversation_id}/stream` for streaming real-time conversation updates. Features include authentication via Bearer token, message polling every 2 seconds, heartbeat messages every 30 seconds, and error handling for connection issues. …
> Create conversation websocket endpoint

- agixt/DB.py
- agixt/MagicalAuth.py
- agixt/Models.py
- agixt/endpoints/Auth.py
- agixt/endpoints/GQL.py
> Revert "feat: Add comprehensive company fields support for xtsystems integration"

- agixt/DB.py
- agixt/MagicalAuth.py
- agixt/Models.py
- agixt/endpoints/Auth.py
- agixt/endpoints/GQL.py
This pull request extends the `Company` model and related API endpoints to support additional company details, such as email, website, address fields, and notes. The changes include updates to the database schema, migration logic, data models, and API input/output handling to ensure these new fields are consistently managed throughout the backend.
**Database and Migration Updates:**
- Added new columns (`email`, `website`, `city`, `state`, `zip_code`, `country`, `notes`) to the `Company` table and updated the migration logic to handle these columns for both SQLite and PostgreSQL databases. [[1]](diffhunk://#diff-acf19d17ca6b49f3682c2080cbd20d6460a9867390a2d65408da7a07fad6ee2cR133-R139) [[2]](diffhunk://#diff-acf19d17ca6b49f3682c2080cbd20d6460a9867390a2d65408da7a07fad6ee2cR986-R992) …
> Add fields to company table

- agixt/Interactions.py
- agixt/XT.py
- agixt/extensions/file_system.py
This PR significantly enhances the `file_system` extension in AGiXT, providing more powerful and flexible file operations that align with modern development practices. The improvements include advanced file search capabilities, line-range reading, content search functionality, and a diff-based file modification system similar to modern code editors.
The existing file_system extension had limited capabilities for file manipulation and search operations. This enhancement addresses the following needs:
- More precise file reading with line range support
- Advanced file search with pattern matching and filtering
- Content search within files with regex support
- Better file modification using diff-based approach instead of simple append
**Before:** Could only read entire files
**After:** …
> Enhance File System Extension

- agixt/WorkerRegistry.py
- agixt/XT.py
- agixt/endpoints/Conversation.py
- docs/stop-conversation-feature.md
This document describes the implementation of a stop conversation feature that allows users to cancel active AI processes/conversations. Fixes #1445 
1. **WorkerRegistry** (`agixt/WorkerRegistry.py`)
- Tracks active conversations and their async tasks
- Provides methods to stop conversations by cancelling their tasks
- Thread-safe implementation using locks
2. **Stop Endpoints** (`agixt/endpoints/Conversation.py`)
- `POST /v1/conversation/{conversation_id}/stop` - Stop a specific conversation
- `POST /v1/conversations/stop` - Stop all active conversations for a user
- `GET /v1/conversations/active` - Get list of active conversations for a user
3. **Integration** (`agixt/XT.py`)
- Modified `chat_completions` method to register/unregister conversations
- Handles `asyncio.CancelledError` …
> Add stop feature to fix 1445

- agixt/Extensions.py
- agixt/WebhookManager.py
- agixt/endpoints/Webhook.py
- agixt/extensions/README.md
- agixt/extensions/notes.py
This PR adds comprehensive webhook support to AGiXT extensions, allowing extension developers to define and emit custom webhook events. This feature enables real-time notifications and integrations when extension operations occur.
- Added `webhook_events` class attribute for extensions to define custom webhook events
- Added `get_extension_webhook_events()` static method to collect webhook events from all loaded extensions
- Extensions can now define webhook events that are automatically discovered and registered
- Refactored `WEBHOOK_EVENT_TYPES` to `CORE_WEBHOOK_EVENT_TYPES` 
- Added `get_all_webhook_event_types()` function to combine core events with extension events
- Maintained backward compatibility with existing `WEBHOOK_EVENT_TYPES`
- Implemented dynamic event type discovery from …
> Add webhook support for extensions

- .gitignore
- Dockerfile
- agixt/Task.py
- agixt/endpoints/Completions.py
- agixt/endpoints/Tasks.py
- agixt/extensions/agixt_actions.py
- agixt/mcp_client.py
- agixt/run-local.py
This document describes the integration of browser-use library with AGiXT through the Model Context Protocol (MCP), enabling AI agents to perform automated web browser interactions through natural language commands.
1. **browser-use MCP Server**: Runs via uvx providing browser automation tools
2. **AGiXT MCP Client**: Built-in MCP client implementation for communication
3. **Browser Automation Command**: AGiXT extension command that orchestrates browser tasks
```mermaid
graph TD
A[AGiXT Agent] --> B[Browser Automation Command]
B --> C[MCP Client]
C --> D[browser-use MCP Server]
D --> E[Playwright Browser]
E --> F[Web Page Interaction]
F --> G[Results]
G --> D
D --> C
C --> B
B --> A
```
Browser automation is now **fully automated** and requires no manual setup! 
The browser automation …
> Enhanced Browser Automation

- agixt/Workspaces.py
- agixt/app.py
The S3 workspace functionality in AGiXT was not working properly, preventing users from using blob storage for workspace persistence. The system was defaulting to local storage even when S3 configuration was provided, and users reported that workspace data was not persisting when using MinIO or other S3-compatible storage backends.
The investigation revealed two critical issues in the workspace implementation:
- The libcloud S3 driver initialization had incorrect SSL and HTTP parameters for MinIO/S3 endpoints
- The `ex_force_http` parameter was incorrectly used, causing connection failures
- SSL handling was not properly configured for HTTP endpoints (like MinIO default setup)
- The `stream_file` method failed to create parent directories before downloading files from S3 to local cache
- …
> Workspace improvements

- agixt/extensions/wordpress.py
This pull request adds a comprehensive WordPress extension to AGiXT, enabling full WordPress site management through the WordPress REST API. The extension is categorized under "Productivity" and provides **52 different commands** for managing all aspects of a WordPress website, including advanced features like custom post types, plugin management, SEO analysis, and content optimization.
- **WORDPRESS_SITE_URL**: Base URL of the WordPress site (e.g., `https://example.com`)
- **WORDPRESS_USERNAME**: WordPress username for authentication  
- **WORDPRESS_APPLICATION_PASSWORD**: WordPress application password (more secure than regular passwords)
- Uses WordPress Application Passwords via HTTP Basic Authentication
- Secure session management with proper error handling
- Graceful fallback for …
> Add WordPress Extension

- agixt/Agent.py
- agixt/Interactions.py
- agixt/extensions/essential_abilities.py
This pull request enhances AGiXT's existing todo system with sophisticated task dependency management and async execution capabilities. Building on the previously merged basic todo functionality, this upgrade adds workflow intelligence and parallel task execution support.
- **Sequential Workflow Support**: Tasks can now depend on completion of other tasks via `depends_on` field
- **Flexible Dependency Format**: Simple comma-separated task ID specification (`"1,2,5"`)
- **Dependency Validation**: Automatic verification that all referenced dependencies exist in conversation
- **Smart Execution Control**: Tasks only become runnable when all dependencies are completed
- **Circular Dependency Prevention**: Validation prevents invalid dependency chains
- **Parallel Task Identification**: Tasks …
> Add async todos

- agixt/extensions/essential_abilities.py
- agixt/extensions/wallet.py
- docker-requirements.txt
- docs/wallet_authentication.md
- requirements.txt
This document describes the complete wallet-based authentication and interaction system for AGiXT, allowing users to log in using their crypto wallets and enabling AI agents to interact with user wallets.
The wallet authentication system provides a complete Web3 integration that:
1. Allows users to authenticate using their crypto wallets (login)
2. Enables AI agents to interact with the user's connected wallet (transactions)
This is implemented as an extension that integrates with AGiXT's existing authentication infrastructure while providing wallet functionality that works with the user's wallet (not the agent's wallet).
- **Agent Wallet** (`solana_wallet.py`): Uses private keys stored during agent creation, can sign transactions directly
- **User Wallet** (`wallet.py`): Never has access …
> Wallet Authentication Implementation
