Josh-XT/AGiXT

- Config.py
After a git clone of this repository, the `agents` directory doesn't exist and function `get_agents` fails. This commit create the directory if it doesn't exist yet.
> Don't fail when `agents` directory doesn't exist. Fix #28

- README.md
Add missing `npm run build` (to create Next pages) in README, for local setup.
> Add frontend build to install instructions

- frontend/components/agent/AgentAdmin.js
- frontend/components/agent/AgentChat.js
- frontend/components/agent/AgentCommand.js
- frontend/components/agent/AgentCommandList.js
- frontend/components/agent/AgentControl.js
- frontend/components/agent/AgentInstruct.js
- frontend/components/agent/AgentObjective.js
- frontend/pages/_app.js
- frontend/pages/agent/[agent].js
- frontend/pages/new_agent.js
Rename environment variable API_URI to NEXT_PUBLIC_API_URI, to allow to customize it, because only environment variables prefixed with NEXT_PUBLIC_ are exposed to the browser (see https://nextjs.org/docs/basic-features/environment-variables#exposing-environment-variables-to-the-browser).
> Prefix API_URI with NEXT_PUBLIC_

- commands/google.py
Use Python syntax instead of TypeScript :) one for an union of to types.
Fixes the following error:
```
ERROR in app: Exception on /api/agent/Agent-LLM/command [GET]
Traceback (most recent call last):
File "~/agent-llm/.venv/lib/python3.9/site-packages/flask/app.py", line 1823, in full_dispatch_request
rv = self.dispatch_request()
File "~/agent-llm/.venv/lib/python3.9/site-packages/flask/app.py", line 1799, in dispatch_request
return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
File "~/agent-llm/.venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 467, in wrapper
resp = resource(*args, **kwargs)
File "~/agent-llm/.venv/lib/python3.9/site-packages/flask/views.py", line 107, in view
return current_app.ensure_sync(self.dispatch_request)(**kwargs)
File …
```
> Use Union[] instead of | for type

- provider/llamacpp.py
Fix:
```
Traceback (most recent call last):
File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
self.run()
File "/usr/lib/python3.9/threading.py", line 892, in run
self._target(*self._args, **self._kwargs)
File "~/agent-llm/AgentLLM.py", line 282, in run_task
task = self.execute_next_task()
File "~/agent-llm/AgentLLM.py", line 254, in execute_next_task
self.response = self.execution_agent(self.primary_objective, this_task_name, this_task_id)
File "~/agent-llm/AgentLLM.py", line 221, in execution_agent
self.response = self.run(prompt)
File "~/agent-llm/AgentLLM.py", line 71, in run
self.response = self.instruct(prompt)
File "~/agent-llm/provider/llamacpp.py", line 20, in instruct
output = self.model.generate(f"Q: {prompt}", n_predict=55, …
```
> Add missing self to llamacpp new_text_callback

- AgentLLM.py
When an agent fails (for example: `llama_generate: error: prompt is too long (2215 tokens, max 1996)`), it returns no result. This PR ensures that a call to `store_result` doesn't raise an exception when result is empty.
So, it fixes the exception below (but doesn't fix the "prompt too long" error that occurs before):
```
llama_generate: error: prompt is too long (2215 tokens, max 1996)
Exception in thread Thread-2:
Traceback (most recent call last):
File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
self.run()
File "/usr/lib/python3.9/threading.py", line 892, in run
self._target(*self._args, **self._kwargs)
File "~/agent-llm/AgentLLM.py", line 282, in run_task
task = self.execute_next_task()
File "~/agent-llm/AgentLLM.py", line 254, in execute_next_task
self.response = …
```
> Don't try to store an empty result

- AgentLLM.py
The order of Config.save_task_output parameters where changed by commit 7c667d6, but the order of the calling arguments where not changed. This commit fixes this.
The exception was:
```
Traceback (most recent call last):
File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
self.run()
File "/usr/lib/python3.9/threading.py", line 892, in run
self._target(*self._args, **self._kwargs)
File "~/agent-llm/AgentLLM.py", line 282, in run_task
task = self.execute_next_task()
File "~/agent-llm/AgentLLM.py", line 257, in execute_next_task
self.response = self.execution_agent(self.primary_objective, this_task_name, this_task_id)
File "~/agent-llm/AgentLLM.py", line 229, in execution_agent
self.update_output_list(f"Execution agent response:\n\n{self.response}")
File …
```
> Fix order of Config.save_task_output args

- docker-compose-mac.yml
Mac users should be able to use this docker-compose file with: 
`docker-compose -f docker-compose-mac.yml up -d --build`
> Add docker-compose for mac #61

- provider/oobabooga.py
Added some error handling for ooba for #81.  The `stripped_string` was trying to strip data if it is none.
> Added some error handling for ooba for #81

- provider/oobabooga.py
Ooba changed their endpoint to `/api/v1/generate` from `/run/textgen` - updated endpoint.
> Ooba endpoint update #93

- Dockerfile-backend
- Dockerfile-mac-backend
- docker-compose-mac.yml
- docker-compose.yml
- docs/README.md
- frontend/Dockerfile
- remove version from registry image so latest tag is always pulled
- include init so processes aren't running as pid 1
-  add optional persistent volumes for agents and workspaces
- Clamp layers from scratch on runner
- move deps from frontend to own build step for faster builds when using cached in CI
> Docker Cleanup

- Dockerfile-backend
- Dockerfile-mac-backend
Since the port has changed to 7437, it should be exposed as well.
> Expose Port 7437 in Dockerfile-backend & Dockerfile-mac-backend

- AgentLLM.py
bit of error checking to prevent a crash if LLM incorrectly formats the arguments in the commands.
> add error checking to prevent crash if LLM parses arguments incorrectly

- Commands.py
- Config.py
Updating Commands.py to fix find_command and execute_command params.
Should solve the commands not working, needs testing.  May fix functionality for broken commands.
App.py runs and doesn't error - not tested past that.
- [ x] My code follows the code style of this project and passes `yarn run lint`.
> Bugfixes - Commands, Fix no objective situation

- AgentLLM.py
It was brought to my attention that `all-MiniLM-L6-v2` cannot embed 500 tokens as I was expecting it to, so I have switched to `distilbert-base-uncased` for non-OpenAI models.  OpenAI still uses Ada.
> Embedding model to distilbert-base-uncased

- Commands.py
Add error handling to command execution to return an error of a command to to agent in the event of a failure instead of causing a crash.
> Add error handling

- provider/huggingchat.py
Huggingchat updated the api code as seen [here](https://huggingface.co/spaces/huggingchat/chat-ui/commit/06e879dcad186431d5527b7de7b3433df5cba230) 
Now you need to pass a json with a model key to the POST request.
> Fix huggingchat provider POST api call

- Commands.py
- commands/file_operations.py
I got the problem with the commands, that was only happening with file_operations.
file_operations methods use one another to achive its goal. The problem is that we don't instantiate the class.
in the commands.py:119, we used to pass the module as a parameter. That will not work for modules on commands where one method depends on the other (since there is no self)
I will up a workaround for that, specific for file_operations, but we need to change the way its done.
> Fix file_operations instatiation

- agixt/AGiXT.py
- agixt/commands/google.py
- DuckDuckGo Search module introduced breaking changes with their last update that broke the search and changed all of the function names to use the search..
- Updated references in `AGiXT.py` and `commands/google.py`
The following is **REQUIRED** if you already have AGiXT installed.
```
pip install duckduckgo_search --upgrade
```
> DuckDuckGo Search Update

- agixt/AGiXT.py
- agixt/commands/searxng_commands.py
Migrate from DDG search to Searxng
- DDG provider has been unreliable on a daily basis, searxng has a number of servers that we can randomly search on.
- Build randomized server selection feature in case the `SEARXNG_INSTANCE_URL` is left blank in agent settings. You can find a list of these at https://searx.space/
> Migrate from DDG search to Searxng

- agixt/Embedding.py
- agixt/Memories.py
- agixt/test-memory.ipynb
- `chroma_db_impl` needs to be `chromadb.db.duckdb.PersistentDuckDB` rather than `duckdb+parquet`, confirmed it only works that way with the latest version of Chroma and Semantic Kernel.
- Huggging Face embedder in Semantic Kernel uses `model_id` rather than `model_name` for the model name, updated ref to fix broken embedder.
> Fix memory issues.

- streamlit/components/history.py
Escape HTML in history to prevent AI responses breaking the history area.
> Escape HTML in history.

- agixt/app.py
Set model to agent name in openai endpoints
- For consistency, we won't add to the OpenAI style endpoints, we will just use the `model` field as suggested in issue #643 .
> Set model to agent name in openai endpoints

- agixt/provider/custom.py
- docs/3-Providers/Azure OpenAI.md
- docs/3-Providers/Custom OpenAI Style Provider.md
- docs/3-Providers/OpenAI.md
Many people are standardizing around using OpenAI endpoints for their providers or utilizing various proxies for various reasons.  The Custom OpenAI Style Provider enables you to use OpenAI proxies as well as custom endpoints that utilize the same syntax as OpenAI's API.
> Add Custom OpenAI Style Provider

- agixt/Agent.py
- streamlit/components/history.py
Improve chat history
- Added timestamps as their own part of the dictionary return.
- Modified the history component in streamlit to improve it.
- Improved history error handling for when agents might not have a history.
> Improve chat history

- ApiClient.ts
- agixt/app.py
- streamlit/ApiClient.py
- streamlit/pages/3-Interact.py
- tests/ApiClient.py
Add parameters to run chain endpoint
- New parameter `all_responses` is default set to `False`, which will make the chain only return the last response from the last step in the chain to the front end.
- New parameter `from_step` is default set to `1`.  This is useful for if you need to start a chain from a specific step instead of from the first step.  Great for debugging your chains if you don't want to have to run every step every time.
> Add parameters to run chain endpoint

- agixt/prompts/gpt-3.5-turbo-16k-0613/instruct.txt
- agixt/prompts/gpt-3.5-turbo-16k/instruct.txt
- agixt/provider/openai.py
Set defaults for OpenAI
- Changed default model to `gpt-3.5-turbo-16k-0613`
- Added prompts for the 16K models.
- Set defaults for temperature and top_p
> Set defaults for OpenAI

- agixt/Embedding.py
- agixt/Interactions.py
- agixt/chains/Ask Helper Agent for Help.json
- agixt/extensions/agixt_agent.py
- agixt/extensions/agixt_chain.py
- agixt/provider/custom.py
- agixt/provider/openai.py
- streamlit/components/selectors.py
- streamlit/pages/0-Agent_Settings.py
- Improve OpenAI Provider to accept custom endpoints for proxies or other providers using the same schema.
- Added the ability to enter your `API_URI` with the OpenAI provider which will allow that endpoint to be used for other providers that are using OpenAI's package for their endpoints.
- Add Helper Agent. This is a new concept for an agent to assist your agent.  You can choose to make it try to help itself.  Recommend giving your agent access to the `Ask for Help or Further Clarification to Complete Task` command 
- Migrated AGiXT extensions to use SDK.
> Improve OpenAI Provider, Add Helper Agent

- .gitignore
- AGiXT.sh
- agixt/launch-backend.sh
- docs/1-Getting started/Quick Start.md
- docs/README.md
The `AGiXT.sh` script will now guide the user through their environment setup by asking them to answer questions that will build the `.env` file required to run AGiXT.
- [Git](https://git-scm.com/downloads)
- [Docker](https://docs.docker.com/get-docker/)
- [Docker Compose](https://docs.docker.com/compose/install/)
- [Python 3.10](https://www.python.org/downloads/)
If using Windows and trying to run locally, it is unsupported, but you will need [Windows Subsystem for Linux](https://docs.microsoft.com/en-us/windows/wsl/install-win10) and [Docker Desktop](https://docs.docker.com/docker-for-windows/install/) at a minimum in addition to the above.
Open a terminal and run the following to download and install AGiXT:
```
git clone https://github.com/Josh-XT/AGiXT
cd AGiXT
./AGiXT.sh
```
During …
> Improved Setup Script

- agixt/Interactions.py
Add interaction log for command execution
- After a command executes, it will now log the command's output as `PYTHON-TERMINAL` in the conversation history.
> Add interaction log for command execution

- agixt/Providers.py
- agixt/providers/petal.py
- agixt/providers/pipeline.py
- requirements.txt
Test removal of torch and transformers requirements
- It seems like the only things using them right now are petal provider and pipeline provider. 
- Added requirements to petal and pipeline provider
- Removed ambiguous function in Providers.py
> Test removal of torch and transformers requirements

- agixt/app.py
- docker-compose-dev.yml
- docker-compose-local-nvidia-sd.yml
- docker-compose-local-nvidia.yml
- docker-compose-postgres-local-nvidia-sd.yml
- docker-compose-postgres-local-nvidia.yml
- docker-compose-postgres.yml
- docker-compose.yml
Add command execution endpoint
- This will enable you to execute any AGiXT command through the `/api/agent/{agent_name}/command` endpoint with a post of the `command_name` and `command_args`.  AGiXT SDK updated to v0.0.25 to add an `execute_command` function.
- Add persistence for WORKSPACE folder for Streamlit app.
> Add command execution endpoint

- agixt/Chains.py
- agixt/Interactions.py
- agixt/app.py
- agixt/db/Agent.py
- agixt/fb/Agent.py
- requirements.txt
Inject conversation name with command executions
- This will make any command executions' outputs show up in the selected conversation history.  The default is `AGiXT Terminal Command Execution` and all messages from commands will show up in the history from `AGiXT Terminal`
> Inject conversation name with command executions

- agixt/Extensions.py
Add DISABLE_EXTENSIONS environment variable
- You can now disable extensions with a comma separated environment variable in the `.env` file called `DISABLE_EXTENSIONS`
- For example:
```
DISABLE_EXTENSIONS=file_system,twitter,discord,searxng
```
This would disable the extensions for file_system, twitter, discord, and searxng.
> Add DISABLE_EXTENSIONS environment variable

- agixt/Extensions.py
- agixt/Interactions.py
- agixt/app.py
- agixt/db/Agent.py
- agixt/fb/Agent.py
Inject agent name into extensions
- This will enable all extensions to access the agent's name for reference at `self.agent_name`
> Inject agent name into extensions

- agixt/app.py
- agixt/readers/arxiv.py
- requirements.txt
Add arXiv reader
- Not in the Web UI or either SDK yet.
- Reads in any arXiv articles based on search query and/or giving it comma separated a list of article IDs.
Search by search query usage:
```python
ArxivReader.write_arxiv_articles_to_memory(query="Large language model data augmentation", max_articles=5)
```
Search by article IDs usage:
```python
ArxivReader.write_arxiv_articles_to_memory(article_ids="2309.07124,2309.07120")
```
> Add arXiv reader

- agixt/Interactions.py
- agixt/readers/arxiv.py
- agixt/readers/file.py
- agixt/readers/website.py
Improve file upload
- Adding a predefined injection variable called `import_files` to be used in prompts, chains, or 
- If `import_files` is recognized in the prompt, a file uploader will be available on the front end to upload multiple files in the chat.
- Inject memories from collection 4 if `import_files` is in the prompt.
- If the file exists in the working directory, `file_content` can be left empty and will be read in.
```
[
{
"file_name.txt": "file_content1",
},
{
"file_name2.txt": "",
},
]
```
> Improve file upload

- agixt/Interactions.py
Rework command execution format
- New format is `#execute_command("Command Name", command_args)` instead of JSON responses being required.  The LLMs can execute commands anywhere in their response and it will be replaced by the output of the command.
```
#execute_command("Command Name", {"arg1: "val1", "arg2": "val2"})
```
> Rework command execution format

- agixt/providers/llamacpp.py
Change defaults for ROPE scaling
- Defaults should be 0 instead of 1000/1
- See more details here: https://github.com/ggerganov/llama.cpp/pull/3401
> Change defaults for ROPE scaling

- agixt/providers/huggingchat.py
- docs/3-Providers/HuggingChat.md
Use pasted cookie instead of file for Huggingchat
- You can just paste in your cookie to the `HUGGINGCHAT_COOKIE` field instead of saving a cookie file now.
> Use pasted cookie instead of file for Huggingchat

- agixt/Memories.py
- agixt/extensions/voice_chat.py
- agixt/prompts/Default/Summarize Content.txt
Memory summarization is a concept that I implemented a long time ago and removed due to the cost of tokens when adding memories. My strategy has improved as well as the models and cost of tokens since then, so I am reintroducing an improved memory summarization concept.
If enabled, the agent will summarize all content before storing it to memory to store the least amount of information as possible without losing any context from the content.
This PR also introduces a new feature that allows you to define an external ChromaDB if you do not want it to be persisted to a file.  Just set environment variables: `CHROMA_HOST`, `CHROMA_PORT`, `CHROMA_API_KEY`, `SSL` 
(true/false).
> Add memory summarization

- agixt/Interactions.py
- Adding `is_m4a_audio` and `is_wav_audio` booleans to the `Interactions`.`run` function. If the `user_input` is passed in as base64 audio, you can set the flag of which type of audio it is and it will automatically transcribe the audio.
- Both new flags are optional and default set to `False`.
```python
response = self.ApiClient.prompt_agent(
agent_name=self.agent_name,
prompt_name="Chat",
prompt_args={
"user_input": base64_audio,
"is_m4a_audio": True,
"conversation_name": self.conversation_name,
},
)
```
> Add audio transcription by boolean

- agixt/Extensions.py
- agixt/extensions/voice_chat.py
The variables `is_m4a_audio` and `is_wav_audio` can be used to target fields in command execution that are populated with base64 audio that needs transcribed to text.
```python
from agixtsdk import AGiXTSDK
sdk = AGiXTSDK( base_uri="http://localhost:7437", api_key="")
base64_audio = get_base64_audio("Today has been a good day!")
response = sdk.execute_command(
agent_name="gpt4free",
command_name="Write to File",
command_args={
"filename": "notes.txt"
"text": base64_audio,
"is_m4a_audio": "text",
},
conversation_name="Test Conversation",
)
print(response)
```
> Add audio transcription to command execution by field

- AGiXT.ps1
- docs/1-Getting started/0-Quick Start.md
- docs/README.md
Add Windows Support
- Switching from the `AGiXT.sh` script to a new `AGiXT.ps1` PowerShell script that will run in Windows, Mac, or Linux as long as PowerShell is installed.
> Add Windows Support

- agixt/extensions/alltalk_tts.py
- agixt/extensions/voice_chat.py
> Script to update the timezone in specified AGiXT Docker Compose files to the current server timezone.

- agixt/extensions/agixt_actions.py
- agixt/prompts/Default/Convert to JSON.txt
Add object converter
- Modified tooling from my [convertanything](https://github.com/DevXT-LLC/convertanything) module and adapted to AGiXT as a command that can be used in chains or by the LLMs. It can convert any unstructured string of information into a `pydantic` model.
- Add `Convert to JSON` prompt template. See template below.
```
**Act as a JSON converter that converts any text into the desired JSON format based on the schema provided. Respond only with JSON in a properly formatted markdown code block, no explanations.**
**Reformat the following information into a structured format according to the schema provided:**
{user_input}
{schema}
JSON Structured Output:
```
> Add object converter

- .github/workflows/code-style-check.yml
- .github/workflows/operation-test-with-jupyter.yml
- .github/workflows/publish-docker-dev.yml
- agixt/Chains.py
- agixt/Embedding.py
- agixt/Interactions.py
- agixt/Memories.py
- agixt/Providers.py
- agixt/endpoints/Memory.py
- agixt/extensions/stable_diffusion.py
- agixt/providers/gemini.py
> Add codestyle checks

- agixt/providers/claude.py
- docs/3-Providers/Anthropic Claude.md
- requirements.txt
Add Claude 3 support to Claude provider
- List of Claude models available at https://docs.anthropic.com/claude/docs/models-overview
- Get your Anthropic API key at https://console.anthropic.com/settings/keys
> Add Claude 3 Support

- agixt/extensions/github.py
- agixt/providers/openai.py
Add day limit to `get_repo_commits`
- Default limit is 7 days, setting to 0 will automatically paginate and get all commits from the repository but takes some time. It took 45 seconds to pull over a year of commits from this repo.
> Add day limit to `get_repo_commits`

- agixt/db/Agent.py
- agixt/fb/Agent.py
Strip backslash on underscore
- Some models are sending backslashes before underscores causing command execution issues with those models.
> Strip backslash on underscore

- agixt/Interactions.py
- agixt/prompts/Default/Command Clarification.txt
Add command clarification
- Adds a new prompt to clarify commands that aren't in the command list against commands in the command list to improve command picking and execution.
- Injected prompt into the `execution_agent` function if a command tried to be executed but wasn't on the list.
```
{COMMANDS}
If you wanted to execute a command like {command_name} with args like {command_args}, which command and args would you choose? Return the proper command execution format filled in following examples.
```
> Add command clarification

- agixt/Interactions.py
- agixt/fb/Agent.py
Switch to execute for command execution
- Previously, the LLMs had to say `#execute_command` which testing has shown to be less effective than switching to `#execute`.
- Improved the command execution prompt.
> Switch to execute for command execution

- agixt/Interactions.py
- agixt/endpoints/Completions.py
Add YouTube captions to link browsing
- If `browse_links` is enabled and a youtube video link is given in the chat, the agent will read the content of the captions for the youtube video linked into memory.
- Set `browse_links` to true by default on the Chat Completions endpoint.  This will make the agent scrape any web URLs the user puts in chat if set to true or not defined.
> Add YouTube captions to link browsing

- agixt/Models.py
- agixt/endpoints/Completions.py
Add agent modes to for additional Chat Completions endpoint functionality
Changes the behavior of the chat completions endpoint when interacting with the agent to either use a prompt template, command, or chain depending on the agent settings.
- Agent setting `mode` can be `prompt`, `command`, or `chain` in the agent's settings.
- If an agent mode is not defined, the chat completions endpoint will use the `Chat` prompt template.
Executes the designated prompt template when interacted with on the chat completions endpoint.
- Requires `prompt_name` and `prompt_category` to also be defined in the agent settings.
- Will use the `user_input` variable in prompt templates to inject the user's input from their message content.
Executes the designated command when interacted with on the chat …
> Add agent modes to for additional Chat Completions endpoint functionality

- docs/2-Concepts/09-Agent Training.md
Added the synthetic dataset generation part and DPO/CPO/ORPO training
> Update 09-Agent Training.md

- agixt/extensions/README.md
- agixt/extensions/agixt_actions.py
- agixt/extensions/discord.py
- agixt/extensions/file_system.py
- agixt/extensions/github.py
- agixt/extensions/google.py
- agixt/extensions/microsoft365.py
- agixt/extensions/mysql_database.py
- agixt/extensions/postgres_database.py
- agixt/extensions/searxng.py
- agixt/extensions/sendgrid_email.py
- agixt/extensions/sqlite_database.py
- agixt/extensions/times.py
- agixt/extensions/web_playwright.py
Add command documentation
- Adds descriptors to each command for further use later.
> Add command documentation

- backend.yml
- docker-compose-dev.yml
- docker-compose.yml
Add LOGLEVEL for #1179
- If you want to change the `LOGLEVEL`, you can add it to your `.env` file.
The default on the stable branch is:
```
LOGLEVEL=ERROR
```
The default on the dev branch is:
```
LOGLEVEL=INFO
```
Options are: CRITICAL, ERROR, WARNING, INFO, DEBUG
> Add LOGLEVEL for #1179

- agixt/extensions/agixt_actions.py
- agixt/prompts/Default/Execution.txt
- agixt/prompts/Default/SmartInstruct-Execution.txt
- agixt/prompts/Default/SmartTask-Execution.txt
- agixt/prompts/Default/Task Execution.txt
The main changes are:
Checking if the task starts with a digit using task[0].isdigit() instead of task[0] in [str(i) for i in range(10)].
Appending the current_task to the new_task_list after the loop ends (instead of inside the loop) to handle the last task correctly.
Removing the check for double newlines ("\n\n") in the current_task as it's not necessary.
The updated function should work correctly to create a task chain from a numbered list of tasks, splitting subtasks properly and handling the last task correctly.
> Improve Logic Create Task Chain and fix commands execution prompts

- agixt/Chain.py
- agixt/XT.py
Parallel chain steps
- Will run prompts in a chain that don't have any requirements from previous steps or context injection in parallel in chains.
> Parallel chain steps

- Dockerfile
- agixt/Agent.py
- agixt/Extensions.py
- agixt/Interactions.py
- agixt/Memories.py
- agixt/Websearch.py
- agixt/XT.py
- agixt/endpoints/Agent.py
- agixt/prompts/Default/Convert to Pydantic Model.txt
- agixt/prompts/Default/Web Summary.txt
- agixt/prompts/Default/WebSearch.txt
- agixt/prompts/Default/Website Summary.txt
- requirements.txt
- static-requirements.txt
Rework websearch to rotate endpoints on failure
- DuckDuckGo added some checks and limits to stop things like AI from searching on their platform. Instead of getting the vision model involved in solving a captcha to move on, I am adding additional search providers for now. 
- Brave search seems to work well so far but may also do the same thing.
- Modified searx functions and created a new `web_search` function that will rotate through a list until it finds a good working search endpoint and saves it to the agent's settings. If that one fails, it will start rotating again until it is searching properly.
- Web search will now rotates through a list of 90+ search providers until one works, then set that one as the agent's search engine until another failure happens.
- Improved keyword …
> Rework websearch to rotate endpoints on failure

- Dockerfile
- agixt/Agent.py
- agixt/Conversations.py
- agixt/Interactions.py
- agixt/Memories.py
- agixt/Prompts.py
- agixt/XT.py
- agixt/prompts/Default/Code Interpreter Multifile.txt
- agixt/prompts/Default/Determine File.txt
- agixt/prompts/Default/Verify Code Interpreter Multifile.txt
- agixt/readers/file.py
- static-requirements.txt
Some file types were identified as needing improvement when chunking into memory while testing. As result, we have several improvements.
When PowerPoints are uploaded, they will be converted to PDF and handled as PDFs are handled.
When a PDF file is uploaded, we typically grab the text from it using `pdfplumber` and chunk the information into memory, which has great results. In addition to that strategy, if a `vision_provider` is selected for the agent, it will also break the PDF up into images per page for the vision model to answer questions about, and any questions answered about images will be retained in conversational memory.
Uploading XLS/XLSX previously would upload the first sheet to memory, it will now iterate over each sheet, convert it to CSV, and then handle each sheet as …
> Improve File Uploads, Vision Always On

- agixt/Agent.py
- agixt/Chain.py
- agixt/MagicalAuth.py
- agixt/Models.py
- agixt/Prompts.py
- agixt/XT.py
- agixt/endpoints/Auth.py
Closing database sessions
- `Agent`, `Chain`, and `Prompts` classes initialized session as `self.session` and never closed the session. Changing to put these 3 classes in line with the others that close sessions.
> Closing database sessions

- agixt/XT.py
- agixt/prompts/Default/Convert Math to Python.txt
- agixt/prompts/Default/Fix Verified Code.txt
- agixt/prompts/Default/Verify Code.txt
- agixt/prompts/Default/Write Code.txt
Add logic to convert math to python to context in chat completions workflow as part of the data analysis functionality.
- Add new agent setting `analyze_user_input` default to `True` if not set.
> Add logic to convert math to python to context in chat completions workflow

- docs/README.md
Fixed With EZLocalAI Sections by adding missing "true" flag to command-line arguments.
Updated the command-line arguments for running AGiXT with ezLocalAI to include the "true" flag. This change affects both the basic usage and the example with additional arguments.
This change is required to ensure correct usage of the `--with-ezlocalai` flag. It solves the problem of potential misuse or confusion when running AGiXT with ezLocalAI.
The changes have been tested by running the updated commands in a local development environment to ensure they work as expected.
N/A
> Update README.md - Fix With EZLocalAI Missing Flag

- agixt/endpoints/Agent.py
Use chat completions on prompt agent endpoint
- Enables the ability to upload files when using the `prompt_agent` function in the SDK by adding `files` to prompt args, which should be in the following format:
```python
files = [
{
"file_name": "filename.pdf",
"file_content": f"data:application/pdf;base64,{pdf_base64}"
}
]
```
> Use chat completions on prompt agent endpoint

- agixt/Conversations.py
- agixt/Models.py
- agixt/endpoints/Conversation.py
- tests/endpoint-tests.ipynb
Add Fork conversation function for #1238 
- Endpoint is `POST /api/conversation/fork`
Input:
```json
{
"conversation_name": "The name of the conversation",
"message_id": "ID of the message to fork the conversation at"
}
```
Output:
```json
{
"message": "The new conversation name from the fork"
}
```
- [Python SDK updated to `v0.0.68`](https://github.com/AGiXT/python-sdk/releases/tag/v0.0.68)
Usage:
```python
from agixtsdk import AGiXTSDK
agixt = AGiXTSDK(base_uri="http://localhost:7437", api_key="Your API Key or JWT", verbose=True)
conversation_name = "Your Conversation"
conversation = agixt.get_conversation(
agent_name=agent_name, conversation_name=conversation_name, limit=100, page=1
)
forked_conversation = agixt.fork_conversation(
conversation_name=conversation_name, …
```
> Add Fork conversation function

- agixt/Extensions.py
- agixt/endpoints/Extension.py
- tests/endpoint-tests.ipynb
The new function will get a list of extensions available to the agent as well as the required settings keys and available commands per extension. 
- If the agent does not have the settings keys for the specific extension, the list of commands will be empty. 
- Each command will also have an `enabled` boolean filled in based on the agent's settings.
- Added `/api/agent/{agent_name}/extensions` endpoint
- Added `get_agent_extensions` function to Python SDK and released [v0.0.69](https://github.com/AGiXT/python-sdk/releases/tag/v0.0.69)
```python
def get_agent_extensions(self, agent_name: str = "AGiXT"):
try:
response = requests.get(
headers=self.headers,
url=f"{self.base_uri}/api/agent/{agent_name}/extensions",
)
if self.verbose:
parse_response(response)
return response.json()["extensions"] …
```
> Add `get_agent_extensions` functionality

- agixt/providers/azure.py
- agixt/providers/openai.py
- docs/3-Providers/0-ezLocalai.md
- docs/3-Providers/1-Anthropic Claude.md
- docs/3-Providers/2-Azure OpenAI.md
- docs/3-Providers/3-Google.md
- docs/3-Providers/4-GPT4Free.md
- docs/3-Providers/5-Hugging Face.md
- docs/3-Providers/6-OpenAI.md
Rewrite Azure OpenAI Provider
- The OpenAI package changes awhile back, I updated the OpenAI provider at that time, but hadn't used the Azure one in awhile. I have converted the Azure OpenAI provider to the format that the OpenAI provider is in.
- Revisited documentation for the Azure OpenAI provider to add more instructions for setup.
> Rewrite Azure OpenAI Provider

- agixt/Globals.py
- agixt/MagicalAuth.py
- docs/README.md
- start.py
Create trained `AGiXT` agent on user registration.
- Added new environment variable `CREATE_AGENT_ON_REGISTER` - If set to `true` (default), every time a user registers, a new agent will be created with the settings from `default_agent.json`
- If you don't have a `default_agent.json` defined, it will use your `ezlocalai` by default if you ran AGiXT with ezlocalai, otherwise, it will default to gpt4free and may or may not work. I unfortunately don't have a reliable free provider yet.
- Added new environment variable `CREATE_AGIXT_AGENT` - If set to `true` (default), every time a user registers, a new agent will be created with the settings from `default_agent.json` ignoring any `training_urls` in the json to train the agent named `AGiXT` on the AGiXT documentation.
**Default `AGiXT` agent …
> Create trained `AGiXT` agent on user registration

- agixt/Models.py
- agixt/XT.py
- agixt/providers/ezlocalai.py
- Added an agent setting for `LANGUAGE` that will allow you to set a language other than English to receive agent responses in. 
- For example, if your agent's language is set to `ru`, it will allow the user to write to the agent in English and receive text output in Russian. This would include the English response as well as the Russian response.
- If you're using `ezLocalai` or another text to speech provider (will expand on this later) for your agent and have it enabled, you will get an output of what you said in the target language as well as the response audio in the target language.
- Improved the function that converts pydantic models to text schemas.
- Currently, the LLM associated with the agent currently is set to handle the text translation, I'm assuming there are significantly …
> Add automatic translations

- .github/workflows/publish-docker-dev.yml
- .github/workflows/publish-docker.yml
- agixt/XT.py
- agixt/prompts/Default/Think About It.txt
- This is disabled by default and is an experimental new feature.
- If you add an agent setting `auto_continue` set to `true`, an additional prompt will go to the agent after it sends the first response asking if it needs to continue writing, rewrite the response, or if it is done. If it needs to continue, it will start from where it left off without acknowledging the additional prompt.
- This will help for long outputs exceeding the typical 4096 limit, effectively extending it to 8192 for models limits to 4096 on output. Some newer models like gpt-4o have 16k output tokens, which would make this increase that to potentially 32k. Some providers tell you why it stopped which will indicate to continue generating or not, but many still do not. This works around the problem for any provider …
> Auto continue, new prompt, and parsing logic updates

- agixt/Interactions.py
- agixt/extensions/agixt_actions.py
Improve command execution and follow ups
This pull request includes changes to the `agixt/Interactions.py` and `agixt/extensions/agixt_actions.py` files to enhance functionality and improve error handling. The most important changes include adding a new rule for command execution order, modifying parameter types, and adding error handling for the `schedule_follow_up` method.
Enhancements and error handling:
* [`agixt/Interactions.py`](diffhunk://#diff-66ea3aae1abe5007b7f1de0b4d4c558a874642fc8338652546e9a26d3c74c5e9R471): Added a rule to ensure all command executions take place before the `<answer>` block in the `format_prompt` method.
* [`agixt/extensions/agixt_actions.py`](diffhunk://#diff-e4be449bc0ebdebe810bb59047122106b4852048d00befdfd56e316f55791c15L216-R218): Changed the parameter …
> Improve command execution and follow ups

- agixt/SeedImports.py
- agixt/readers/file.py
This pull request includes several changes to the `agixt/SeedImports.py` file to improve the import process for agents, extensions, chains, prompts, and providers. The changes include adding checks to prevent duplicate entries, ensuring a default user exists, and refactoring the code for better readability and maintainability.
* Added a new function `ensure_default_user` to ensure the default admin user exists.
* Modified `import_agents`, `import_extensions`, `import_chains`, `import_prompts`, and `import_providers` functions to include checks for existing entries before adding new ones to prevent duplicates. [[1]](diffhunk://#diff-e988e958c4e5ee83d0864df052d6716e3fc6a34ca586119bd3559a981ca9de7fR64) [[2]](diffhunk://#diff-e988e958c4e5ee83d0864df052d6716e3fc6a34ca586119bd3559a981ca9de7fL58- …
> improve import seeding

- agixt/Interactions.py
This pull request includes a significant refactor of the command and answer handling logic in the `run` method of the `agixt/Interactions.py` file. The changes aim to improve the structure and readability of the code while ensuring that commands and responses are processed more efficiently.
Key changes include:
* Introduced a `processed_length` variable to track the length of the response that has been processed, ensuring that only new content is processed in each iteration.
* Added an initial command execution check to handle any commands present in the initial response before entering the main processing loop.
* Refactored the main processing loop to check for new commands and process them only if new content is detected, reducing unnecessary iterations.
* Improved the handling of the …
> Prevent duplicate executions

- agixt/providers/agixt.py
- agixt/providers/anthropic.py
- agixt/providers/azure.py
- agixt/providers/default.py
- agixt/providers/ezlocalai.py
- agixt/providers/google.py
- agixt/providers/gpt4free.py
- agixt/providers/huggingface.py
- agixt/providers/openai.py
- agixt/providers/rotation.py
- docs/3-Providers/0-ezLocalai.md
- docs/3-Providers/1-Anthropic Claude.md
- docs/3-Providers/2-Azure OpenAI.md
- docs/3-Providers/3-xAI.md
- docs/3-Providers/4-Google.md
- docs/3-Providers/5-Hugging Face.md
- docs/3-Providers/6-OpenAI.md
- docs/3-Providers/7-GPT4Free.md
This pull request includes several updates to the `agixt/providers` module, primarily focusing on renaming classes and parameters to improve clarity and consistency across different providers. Additionally, a new `RotationProvider` class has been introduced.
The most important changes include:
* [`agixt/providers/anthropic.py`](diffhunk://#diff-fc2b8c871c5a2e50430e4ec349433d7e2ebdde80f72c71daffc2cda45621e01dL16-L38): Renamed class from `ClaudeProvider` to `AnthropicProvider` and updated parameter names to include `ANTHROPIC_` prefix.
* [`agixt/providers/azure.py`](diffhunk://#diff-92baeda7230d8a4f2637da8e4cc302a5ce0e20d02d137585ea8f70764fd36f14L12-R30): Updated parameter names to include `AZURE_` prefix.
* [`agixt/providers/default.py`](diffhunk://#diff-39a9c71d7737bbd68e337eaf5a5f53b3be8e …
> Add rotation provider

- agixt/Conversations.py
- agixt/DB.py
This pull request includes significant improvements to the `agixt` package, focusing on optimizing database queries, adding timestamp columns, and ensuring safe migrations. The most important changes include optimizing the retrieval of conversations, updating timestamps on interactions, and adding a migration script for SQLite databases.
Optimizations and new features:
* [`agixt/Conversations.py`](diffhunk://#diff-791e06557a48c657e0d1c3eac5aca99792f28772835f5dd7d08d9b3e64929e26R79-R111): Optimized the `get_conversations` and `get_conversations_with_ids` methods to use a single query with a join to retrieve only conversations with messages, and ordered the results by the `updated_at` timestamp.
* [`agixt/Conversations.py`](diffhunk://#diff-791e06557a48c657e0d1c3eac5aca99792f28772835f5dd7d08 …
> Add dates to conversations

- agixt/Memories.py
This pull request includes a significant update to the `agixt/Memories.py` file, specifically enhancing the `write_text_to_memory` function to handle duplicate content from external sources. The most important changes are:
Enhancements to duplicate content handling:
* Added logic to check for duplicates from external sources such as files or URLs. If a duplicate is found, the existing content from that source is deleted before writing the new content. This ensures that the memory does not contain redundant information.
> Deduplicate memories existing by external sources

- agixt/Conversations.py
- agixt/Models.py
- agixt/endpoints/Conversation.py
This pull request introduces several changes to enhance the conversation management feature in the `agixt` project. The most important changes include adding a new method to retrieve detailed conversations, updating the `HistoryModel` to make `conversation_name` optional, and adding new endpoints for fetching conversation details and history.
* Added `get_conversations_with_detail` method in `Conversations.py` to retrieve conversations along with their messages using a LEFT OUTER JOIN.
* Updated `HistoryModel` in `Models.py` to make `conversation_name` an optional field.
* Modified imports in `Conversation.py` to include `get_conversation_name_by_id` from `Conversations` and `MagicalAuth`. [[1]](diffhunk://#diff-ab7556e3f67cbeadf9f9bb4966a9d7ebc94a8194b866cd5068eb7b543e194facL2-R3) …
> Add more detailed conversation endpoints

- agixt/Interactions.py
- agixt/Websearch.py
- agixt/XT.py
- agixt/extensions/agixt_actions.py
This pull request introduces several changes to the `agixt` project, focusing on enhancing the logging of interactions and adding new functionalities for data analysis and web search. The most important changes include the addition of `thinking_id` for logging subactivities, the introduction of new commands in `agixt_actions`, and updates to various methods to incorporate these changes.
Enhancements to logging:
* [`agixt/Interactions.py`](diffhunk://#diff-66ea3aae1abe5007b7f1de0b4d4c558a874642fc8338652546e9a26d3c74c5e9R230-R233): Added `thinking_id` to log subactivities in multiple methods such as `format_prompt`, `run`, and others. [[1]](diffhunk://#diff-66ea3aae1abe5007b7f1de0b4d4c558a874642fc8338652546e9a26d3c74c5e9R230-R233) [[2]](diffhunk://#diff-66ea3aae1abe5007b7f1de0b4d4c558a874642 …
> Add commands for data analysis and websearch, improve subactivities

- agixt/Conversations.py
- agixt/DB.py
- agixt/endpoints/Conversation.py
This pull request introduces several enhancements to the conversation management system, focusing on notification handling and message logging. The most important changes include adding notification checks to conversation queries, implementing a method to retrieve notifications, and updating the message logging process to handle notifications.
Enhancements to conversation management:
* [`agixt/Conversations.py`](diffhunk://#diff-791e06557a48c657e0d1c3eac5aca99792f28772835f5dd7d08d9b3e64929e26L122-L129): Modified `get_conversations_with_detail` to include a notification count for each conversation and added a `has_notifications` field to the result. [[1]](diffhunk://#diff-791e06557a48c657e0d1c3eac5aca99792f28772835f5dd7d08d9b3e64929e26L122-L129) …
> Add notifications

- agixt/providers/coding.py
This pull request introduces a new `CodingProvider` class in the `agixt/providers/coding.py` file, which allows users to offload coding tasks to a specified coding provider while maintaining a default provider for other tasks.
Key changes include:
* **New Class Introduction**:
* [`CodingProvider`](diffhunk://#diff-d72c46e889a403965286a8bf111475c2312ee5b5d0000185fd38c206cded30a2R1-R77): A new class that allows users to specify a default provider and a separate coding provider for handling coding tasks. It includes methods for initializing the provider settings and performing inference based on the type of task.
* **Error Handling**:
* Enhanced error handling within the `inference` method to switch between the default provider and the coding provider in case of failures. This ensures …
> Add coding provider

- agixt/Agent.py
- agixt/Interactions.py
- agixt/Task.py
This pull request introduces new methods to handle task retrieval for agents and integrates these methods into the interaction formatting process. The most important changes include the addition of new methods in `agixt/Agent.py`, the integration of task retrieval in `agixt/Interactions.py`, and the removal of an outdated method in `agixt/Task.py`.
* [`agixt/Agent.py`](diffhunk://#diff-556d8be092ab95b9c185df744d2b3c8f7ad8652b5819506599877fd2a9cead8dR754-R801): Added `get_conversation_tasks` method to retrieve tasks related to a specific conversation and format them in markdown.
* [`agixt/Agent.py`](diffhunk://#diff-556d8be092ab95b9c185df744d2b3c8f7ad8652b5819506599877fd2a9cead8dR754-R801): Added `get_all_pending_tasks` method to retrieve all pending tasks for an agent.
* …
> Inject pending tasks to context

- agixt/Conversations.py
- agixt/DB.py
- agixt/XT.py
- agixt/prompts/Default/Summarize Conversation.txt
This pull request introduces enhancements to the conversation management and database schema in the `agixt` project. The key changes include adding support for conversation summaries and attachment counts, updating the database schema to include these new fields, and ensuring the conversation summary is updated during interactions.
Enhancements to conversation management:
* [`agixt/Conversations.py`](diffhunk://#diff-791e06557a48c657e0d1c3eac5aca99792f28772835f5dd7d08d9b3e64929e26R1101-R1213): Added methods `set_conversation_summary`, `get_conversation_summary`, `get_attachment_count`, `update_attachment_count`, and `increment_attachment_count` to manage conversation summaries and attachment counts.
* [`agixt/Conversations.py`](diffhunk://#diff-791e06557a48c657e0d1c3eac5aca99792f28772835f5 …
> Auto summarize conversations, add attachment count

- agixt/Memories.py
Fixes [https://github.com/Josh-XT/AGiXT/security/code-scanning/316](https://github.com/Josh-XT/AGiXT/security/code-scanning/316)
To fix the problem, we need to ensure that the `file_path` derived from `external_source` is properly validated and sanitized. We can achieve this by normalizing the `file_path` and ensuring it is contained within the `working_directory`. This will prevent directory traversal attacks and ensure that only files within the intended directory can be deleted.
1. Normalize the `file_path` using `os.path.normpath` to remove any ".." segments.
2. Check that the normalized `file_path` starts with the `working_directory`.
_Suggested fixes powered by Copilot Autofix. Review carefully before merging._
> Fix code scanning alert no. 316: Uncontrolled data used in path expression

- agixt/extensions/graphql_server.py
- requirements.txt
This pull request introduces a new extension to interact with a GraphQL API endpoint in the `agixt/extensions/graphql_server.py` file. The key changes include the addition of a new class `graphql_server`, methods to execute GraphQL queries, fetch the GraphQL schema, and chat with the GraphQL server using natural language.
New extension for GraphQL interaction:
* Added `graphql_server` class to enable interaction with a GraphQL API endpoint, with default connection to the AGiXT GraphQL server.
* Implemented `execute_query` method to perform custom GraphQL queries and handle errors by reformatting invalid queries.
* Added `get_schema` method to retrieve the GraphQL server schema using introspection and format it into a readable format.
* Introduced `chat_with_graphql` method to generate and …
> Add graphql extensions

- agixt/endpoints/GQL.py
This pull request includes changes to the `agixt/endpoints/GQL.py` file to modify the `get_user_from_context` function calls. The changes ensure that additional variables `auth` and `magical` are retrieved along with the `user`.
Key changes include:
* Updated `providers` method to retrieve `auth` and `magical` from `get_user_from_context` function.
* Updated `extension_settings` method to retrieve `auth` and `magical` from `get_user_from_context` function.
* Updated `chains` method to retrieve `auth` and `magical` from `get_user_from_context` function.
* Updated `chain_args` method to retrieve `auth` and `magical` from `get_user_from_context` function.
> Fix #1371 : Chain Query `too many values`

- agixt/endpoints/GQL.py
Fixes #1367 : `Providers` has Nested GQL Key
This pull request includes changes to the `agixt/endpoints/GQL.py` file, focusing on simplifying the code structure and improving type consistency. The most important changes involve the removal of the `Providers` class and the modification of the `providers` method to return a list directly.
Code simplification and type consistency improvements:
* Removed the `Providers` class, which previously encapsulated a list of `ProviderDetail` objects.
* Modified the `providers` method to return a `List[ProviderDetails]` directly instead of an instance of the removed `Providers` class.
> Fix #1367 : `Providers` has Nested GQL Key

- agixt/Chain.py
Fix #1370: Implement IDs for Chains in GQL
This pull request includes a small change to the `agixt/Chain.py` file. The change adds the `id` field to the dictionary being appended to the `chain_list` in the `get_user_chains` method.
* [`agixt/Chain.py`](diffhunk://#diff-bbe0ac321f660f213836db675911928e8a1db165b12d6cbaceb2eae96f8ab160R138): Added the `id` field to the dictionary in the `get_user_chains` method.
> Fix #1370: Implement IDs for Chains in GQL

- agixt/endpoints/Chain.py
Fix #1369: Chains Allow Empty Names
This pull request focuses on adding validation checks to ensure that the `chain_name` parameter is not empty in various endpoint functions within the `agixt/endpoints/Chain.py` file. Each affected function now raises an `HTTPException` with a status code of 400 if the `chain_name` is empty, improving the robustness and reliability of the code.
Validation improvements:
* Added a check to raise an `HTTPException` if `chain_name` is empty in the `get_chain` function.
* Added a check to raise an `HTTPException` if `chain_name` is empty in the `run_chain` function.
* Added a check to raise an `HTTPException` if `chain_name` is empty in the `run_chain_step` function.
* Added a check to raise an `HTTPException` if `chain_name` is empty in the `get_chain_args` …
> Fix #1369: Chains Allow Empty Names

- agixt/Chain.py
This fix is related to the issue AGiXT/Interactive#48
> fix: ensure target_id assignment in Chain.py

- agixt/Interactions.py
Fixes #1412 
This pull request introduces a significant enhancement to the `run` method in the `agixt/Interactions.py` file. The main change is the addition of a mechanism to handle broken file references in the response by searching for and replacing them with the most similar or recently modified files in the directory.
* Added logic to detect broken file references in the response and attempt to replace them with the most similar or recently modified files in the working directory.
* Implemented a similarity check using `SequenceMatcher` to find the best matching file when the exact file is not found.
* Added a fallback mechanism to prefer recently created files (within the last 5 minutes) over similar names if available.
* Updated the response to replace broken links with the found …
> Force output URLs to use existing files if local

- agixt/extensions/agixt_actions.py
This pull request introduces a new method for AGiXT agents to interact with MCP servers. 
New functionality:
* [`agixt/extensions/agixt_actions.py`](diffhunk://#diff-e4be449bc0ebdebe810bb59047122106b4852048d00befdfd56e316f55791c15R1340-R1390): Added a new method `mcp_client` to interact with Model Context Protocol (MCP) servers. This method includes arguments for `endpoint_url`, `api_key`, `user_input`, `context`, and `tools`, and returns the server's response or an error message.
Updates to initialization:
* [`agixt/extensions/agixt_actions.py`](diffhunk://#diff-e4be449bc0ebdebe810bb59047122106b4852048d00befdfd56e316f55791c15R181): Updated the `__init__` method to include the new `Use MCP Server` command, which maps to the `mcp_client` method.
> Add MCP Server Compatibility

- docs/2-Concepts/0-Core Concepts.md
- docs/2-Concepts/01-Processes and Frameworks.md
Hi! I updated all documentation links in `0-Core Concepts.md` and `01-Processes and Frameworks.md`
...
...
...
> fix: broken links in docs

- agixt/extensions/microsoft.py
Small PR - evaluates the Outlook timezone in headers dict.
> fix: evaluate Outlook timezone in headers

- agixt/extensions/agixt_actions.py
This pull request introduces a new feature to the `agixt_actions.py` file, allowing for custom API calls. The changes include adding a new method for making API requests and updating the command mapping to include this functionality.
* Added a new method `custom_api` to enable making custom API calls. This method accepts an API endpoint URL, a payload, and headers, processes them, and sends a POST request. It also handles exceptions and logs errors. (`agixt/extensions/agixt_actions.py`, [agixt/extensions/agixt_actions.pyR1633-R1660](diffhunk://#diff-e4be449bc0ebdebe810bb59047122106b4852048d00befdfd56e316f55791c15R1633-R1660))
* Updated the `__init__` method to include the "Custom API Endpoint" command in the command mapping, linking it to the newly added `custom_api` method. …
> Add custom API command

- agixt/DB.py
- agixt/MagicalAuth.py
- agixt/Models.py
- agixt/endpoints/Auth.py
- agixt/endpoints/GQL.py
This PR adds comprehensive support for additional company contact and address fields to AGiXT to support the xtsystems integration and resolve missing database fields in company management.
Related Issue: Supports DevXT-LLC/xtsystems#66
Key Changes:
- Added email, website, city, state, zip_code, country, notes, parent_company_id fields to Company DB model
- Added parent-child company relationship with foreign key constraint
- Updated CompanyResponse and UpdateCompanyInput Pydantic models
- Enhanced MagicalAuth update_company method to handle all new fields
- Updated GraphQL models and endpoints
- Added database migration function with automatic schema updates
- Supports both SQLite and PostgreSQL databases
All new fields are optional and nullable for backward compatibility.
Files …
> feat: Add comprehensive company fields support for xtsystems integration

- agixt/Models.py
- agixt/endpoints/Agent.py
This PR adds a new endpoint that enables or disables all commands for a specific extension for a specific agent with a single API call, providing convenient bulk operations for extension management.
- Added `ToggleExtensionCommandsPayload` model with:
- `extension_name: str` - The name of the extension to toggle
- `enable: bool` - Whether to enable or disable all commands
- **Route**: `PATCH /v1/agent/{agent_id}/extension/commands`
- **Purpose**: Toggle all commands for a specific extension using agent ID
- **Authentication**: Requires admin privileges
- **Request Body**:
```json
{
"extension_name": "websearch",
"enable": true
}
```
- **Response**: Returns success message with count of affected commands
- **Error Handling**: Returns 404 if extension not found or has no commands
The …
> Add Extension Command Bulk Toggle Endpoint
